// packages/react/src/tier3/Carousel.tsx
import React, { createContext, useCallback, useContext, useRef } from 'react'
import { createCarousel, type Carousel as CarouselMachine } from '@web-loom/foolscap-core'
import { useMachine } from '../hooks/useMachine'
import { useCallbackRef } from '../utils/useCallbackRef'
import { cx } from '../utils/cx'

interface CarouselContextValue {
  machine: CarouselMachine
  slides: React.ReactNode[]
  injectRootEl: (el: HTMLElement | null) => void
  injectSlideEl: (index: number, el: HTMLDivElement | null) => void
}

const CarouselContext = createContext<CarouselContextValue | null>(null)

function useCarouselContext(): CarouselContextValue {
  const ctx = useContext(CarouselContext)
  if (!ctx) throw new Error('Carousel components must be used inside CarouselRoot')
  return ctx
}

export interface CarouselRootProps
  extends Omit<React.HTMLAttributes<HTMLElement>, 'children' | 'onChange'>,
    React.RefAttributes<HTMLElement> {
  slides: React.ReactNode[]
  label: string
  index?: number
  initialIndex?: number
  loop?: boolean
  autoPlay?: boolean
  autoPlayInterval?: number
  onSlideChange?: (index: number, prevIndex: number) => void
  className?: string
  children?: React.ReactNode
}

export function CarouselRoot({
  slides,
  label,
  index,
  initialIndex,
  loop = false,
  autoPlay = false,
  autoPlayInterval,
  onSlideChange,
  className,
  children,
  ref,
  ...props
}: CarouselRootProps) {
  const slidesRef = useRef(slides)
  slidesRef.current = slides
  const labelRef = useRef(label)
  labelRef.current = label
  const indexRef = useRef(index)
  indexRef.current = index
  const initialIndexRef = useRef(initialIndex)
  const loopRef = useRef(loop)
  loopRef.current = loop
  const autoPlayRef = useRef(autoPlay)
  autoPlayRef.current = autoPlay
  const autoPlayIntervalRef = useRef(autoPlayInterval)
  autoPlayIntervalRef.current = autoPlayInterval
  const stableOnSlideChange = useCallbackRef(onSlideChange)

  const machine = useMachine(() =>
    createCarousel({
      get slideCount() {
        return slidesRef.current.length
      },
      get label() {
        return labelRef.current
      },
      get index() {
        return indexRef.current
      },
      initialIndex: initialIndexRef.current,
      get loop() {
        return loopRef.current
      },
      get autoPlay() {
        return autoPlayRef.current
      },
      get autoPlayInterval() {
        return autoPlayIntervalRef.current
      },
      onSlideChange: stableOnSlideChange,
    })
  )

  const injectRootEl = useCallback((el: HTMLElement | null) => machine.setRootEl(el), [machine])
  const injectSlideEl = useCallback((slideIndex: number, el: HTMLDivElement | null) => {
    machine.setSlideEl(slideIndex, el)
  }, [machine])
  const rootProps = machine.getRootProps()

  return (
    <CarouselContext.Provider value={{ machine, slides, injectRootEl, injectSlideEl }}>
      <section
        {...props}
        role={rootProps.role}
        aria-roledescription={rootProps['aria-roledescription']}
        aria-label={props['aria-label'] ?? rootProps['aria-label']}
        aria-live={rootProps['aria-live']}
        data-state={rootProps['data-state']}
        data-loop={rootProps['data-loop']}
        data-autoplay={rootProps['data-autoplay']}
        onMouseEnter={rootProps.onMouseEnter}
        onMouseLeave={rootProps.onMouseLeave}
        onFocus={rootProps.onFocusIn}
        onBlur={rootProps.onFocusOut}
        ref={(el) => {
          injectRootEl(el)
          if (typeof ref === 'function') ref(el)
          else if (ref) (ref as React.MutableRefObject<HTMLElement | null>).current = el
        }}
        className={cx('fc-carousel', className)}
      >
        {children ?? (
          <>
            <CarouselViewport />
            <CarouselControls />
            <CarouselIndicators />
          </>
        )}
      </section>
    </CarouselContext.Provider>
  )
}

export interface CarouselViewportProps extends React.HTMLAttributes<HTMLDivElement> {
  className?: string
}

export function CarouselViewport({ className, children, ...props }: CarouselViewportProps) {
  const { machine, slides, injectSlideEl } = useCarouselContext()
  return (
    <div {...props} className={cx('fc-carousel__viewport', className)}>
      <div className="fc-carousel__track">
        {children ??
          slides.map((slide, index) => {
            const slideProps = machine.getSlideProps(index)
            return (
              <div
                key={index}
                role={slideProps.role}
                aria-roledescription={slideProps['aria-roledescription']}
                aria-label={slideProps['aria-label']}
                data-state={slideProps['data-state']}
                ref={(el) => injectSlideEl(index, el)}
                className="fc-carousel__slide"
              >
                {slide}
              </div>
            )
          })}
      </div>
    </div>
  )
}

export interface CarouselControlsProps extends React.HTMLAttributes<HTMLDivElement> {
  className?: string
}

export function CarouselControls({ className, ...props }: CarouselControlsProps) {
  return (
    <div {...props} className={cx('fc-carousel__controls', className)}>
      <CarouselPrev />
      <CarouselNext />
    </div>
  )
}

export interface CarouselButtonProps extends Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, 'type'> {
  className?: string
}

export function CarouselPrev({ className, children = '‹', onClick, onKeyDown, ...props }: CarouselButtonProps) {
  const { machine } = useCarouselContext()
  const prevProps = machine.getPrevProps()
  return (
    <button
      {...props}
      type={prevProps.type}
      aria-label={props['aria-label'] ?? prevProps['aria-label']}
      aria-disabled={prevProps['aria-disabled']}
      disabled={prevProps.disabled}
      onClick={(e) => {
        onClick?.(e)
        if (!e.defaultPrevented) prevProps.onClick()
      }}
      onKeyDown={(e) => {
        onKeyDown?.(e)
        if (!e.defaultPrevented) prevProps.onKeyDown(e.nativeEvent)
      }}
      className={cx('fc-carousel__prev', className)}
    >
      {children}
    </button>
  )
}

export function CarouselNext({ className, children = '›', onClick, onKeyDown, ...props }: CarouselButtonProps) {
  const { machine } = useCarouselContext()
  const nextProps = machine.getNextProps()
  return (
    <button
      {...props}
      type={nextProps.type}
      aria-label={props['aria-label'] ?? nextProps['aria-label']}
      aria-disabled={nextProps['aria-disabled']}
      disabled={nextProps.disabled}
      onClick={(e) => {
        onClick?.(e)
        if (!e.defaultPrevented) nextProps.onClick()
      }}
      onKeyDown={(e) => {
        onKeyDown?.(e)
        if (!e.defaultPrevented) nextProps.onKeyDown(e.nativeEvent)
      }}
      className={cx('fc-carousel__next', className)}
    >
      {children}
    </button>
  )
}

export interface CarouselIndicatorsProps extends React.HTMLAttributes<HTMLDivElement> {
  className?: string
}

export function CarouselIndicators({ className, onKeyDown, ...props }: CarouselIndicatorsProps) {
  const { machine, slides } = useCarouselContext()
  const indicatorsProps = machine.getIndicatorsProps()
  return (
    <div
      {...props}
      role={indicatorsProps.role}
      aria-label={props['aria-label'] ?? indicatorsProps['aria-label']}
      onKeyDown={(e) => {
        onKeyDown?.(e)
        if (!e.defaultPrevented) indicatorsProps.onKeyDown(e.nativeEvent)
      }}
      className={cx('fc-carousel__indicators', className)}
    >
      {slides.map((_, index) => (
        <CarouselIndicator key={index} index={index} />
      ))}
    </div>
  )
}

export interface CarouselIndicatorProps extends Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, 'type'> {
  index: number
  className?: string
}

export function CarouselIndicator({ index, className, children, onClick, ...props }: CarouselIndicatorProps) {
  const { machine } = useCarouselContext()
  const indicatorProps = machine.getIndicatorProps(index)
  return (
    <button
      {...props}
      type={indicatorProps.type}
      role={indicatorProps.role}
      aria-label={props['aria-label'] ?? indicatorProps['aria-label']}
      aria-selected={indicatorProps['aria-selected']}
      aria-current={indicatorProps['aria-current']}
      tabIndex={indicatorProps.tabIndex}
      data-state={indicatorProps['data-state']}
      onClick={(e) => {
        onClick?.(e)
        if (!e.defaultPrevented) indicatorProps.onClick()
      }}
      className={cx('fc-carousel__indicator', className)}
    >
      {children}
    </button>
  )
}

// packages/angular/src/tier3/Carousel.ts
import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  EventEmitter,
  inject,
  InjectionToken,
  Injector,
  Input,
  type OnInit,
  Output,
  runInInjectionContext,
  signal,
} from '@angular/core'
import { createCarousel, type Carousel as CarouselMachine } from '@web-loom/foolscap-core'
import { injectMachine } from '../bindings/inject-machine'
import { injectStableCallback } from '../bindings/inject-stable-callback'

export const CAROUSEL = new InjectionToken<CarouselRoot>('fc-carousel')

function injectCarousel(): CarouselRoot {
  const ctx = inject(CAROUSEL, { optional: true })
  if (!ctx) throw new Error('Carousel components must be used inside CarouselRoot')
  return ctx
}

export interface CarouselRootProps {
  slides: string[]
  label: string
  index?: number
  initialIndex?: number
  loop?: boolean
  autoPlay?: boolean
  autoPlayInterval?: number
}

export interface CarouselIndicatorProps {
  index: number
}

@Component({
  selector: 'button[fc-carousel-prev]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-carousel__prev',
    '[attr.type]': 'prevProps.type',
    '[attr.aria-label]': 'ariaLabel ?? prevProps["aria-label"]',
    '[attr.aria-disabled]': 'prevProps["aria-disabled"]',
    '[disabled]': 'prevProps.disabled',
    '(click)': 'prevProps.onClick()',
    '(keydown)': 'prevProps.onKeyDown($event)',
  },
})
export class CarouselPrev {
  private readonly ctx = injectCarousel()
  @Input('aria-label') ariaLabel?: string
  get prevProps() {
    void this.ctx.current()
    return this.ctx.machine.getPrevProps()
  }
}

@Component({
  selector: 'button[fc-carousel-next]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-carousel__next',
    '[attr.type]': 'nextProps.type',
    '[attr.aria-label]': 'ariaLabel ?? nextProps["aria-label"]',
    '[attr.aria-disabled]': 'nextProps["aria-disabled"]',
    '[disabled]': 'nextProps.disabled',
    '(click)': 'nextProps.onClick()',
    '(keydown)': 'nextProps.onKeyDown($event)',
  },
})
export class CarouselNext {
  private readonly ctx = injectCarousel()
  @Input('aria-label') ariaLabel?: string
  get nextProps() {
    void this.ctx.current()
    return this.ctx.machine.getNextProps()
  }
}

@Component({
  selector: '[fc-carousel-controls]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CarouselPrev, CarouselNext],
  template: `
    <button fc-carousel-prev>‹</button>
    <button fc-carousel-next>›</button>
  `,
  host: { class: 'fc-carousel__controls' },
})
export class CarouselControls {
  readonly kind = 'controls'
}

@Component({
  selector: 'button[fc-carousel-indicator]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-carousel__indicator',
    '[attr.type]': 'indicatorProps.type',
    '[attr.role]': 'indicatorProps.role',
    '[attr.aria-label]': 'indicatorProps["aria-label"]',
    '[attr.aria-selected]': 'indicatorProps["aria-selected"]',
    '[attr.aria-current]': 'indicatorProps["aria-current"]',
    '[attr.tabindex]': 'indicatorProps.tabIndex',
    '[attr.data-state]': 'indicatorProps["data-state"]',
    '(click)': 'indicatorProps.onClick()',
  },
})
export class CarouselIndicator {
  private readonly ctx = injectCarousel()
  private readonly cdr = inject(ChangeDetectorRef)

  @Input({ required: true }) index = 0

  constructor() {
    queueMicrotask(() => this.ctx.machine.subscribe(() => this.cdr.markForCheck()))
  }
  get indicatorProps() {
    void this.ctx.current()
    return this.ctx.machine.getIndicatorProps(this.index)
  }
}

@Component({
  selector: '[fc-carousel-indicators]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CarouselIndicator],
  template: `
    @for (slide of ctx.slides; track $index) {
      <button fc-carousel-indicator [index]="$index"></button>
    }
  `,
  host: {
    class: 'fc-carousel__indicators',
    '[attr.role]': 'indicatorsProps.role',
    '[attr.aria-label]': 'indicatorsProps["aria-label"]',
    '(keydown)': 'indicatorsProps.onKeyDown($event)',
  },
})
export class CarouselIndicators {
  readonly ctx = injectCarousel()
  get indicatorsProps() {
    return this.ctx.machine.getIndicatorsProps()
  }
}

@Component({
  selector: '[fc-carousel-viewport]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="fc-carousel__track">
      @for (slide of ctx.slides; track $index) {
        <div
          class="fc-carousel__slide"
          [attr.role]="slideProps($index).role"
          [attr.aria-roledescription]="slideProps($index)['aria-roledescription']"
          [attr.aria-label]="slideProps($index)['aria-label']"
          [attr.data-state]="slideProps($index)['data-state']"
        >
          {{ slide }}
        </div>
      }
    </div>
  `,
  host: { class: 'fc-carousel__viewport' },
})
export class CarouselViewport implements OnInit {
  readonly ctx = injectCarousel()
  private readonly el = inject(ElementRef<HTMLElement>)
  private readonly cdr = inject(ChangeDetectorRef)

  ngOnInit(): void {
    this.ctx.machine.subscribe(() => this.cdr.markForCheck())
    queueMicrotask(() => {
      this.el.nativeElement.querySelectorAll('.fc-carousel__slide').forEach((node: Element, index: number) => {
        this.ctx.machine.setSlideEl(index, node instanceof HTMLDivElement ? node : null)
      })
    })
  }

  slideProps(index: number) {
    void this.ctx.current()
    return this.ctx.machine.getSlideProps(index)
  }
}

@Component({
  selector: 'section[fc-carousel], fc-carousel',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CarouselViewport, CarouselControls, CarouselIndicators],
  template: `
    <div fc-carousel-viewport></div>
    <div fc-carousel-controls></div>
    <div fc-carousel-indicators></div>
  `,
  host: {
    class: 'fc-carousel',
    '[attr.role]': 'rootProps.role',
    '[attr.aria-roledescription]': 'rootProps["aria-roledescription"]',
    '[attr.aria-label]': 'label',
    '[attr.aria-live]': 'rootProps["aria-live"]',
    '[attr.data-state]': 'rootProps["data-state"]',
    '[attr.data-loop]': 'rootProps["data-loop"]',
    '[attr.data-autoplay]': 'rootProps["data-autoplay"]',
    '(mouseenter)': 'rootProps.onMouseEnter()',
    '(mouseleave)': 'rootProps.onMouseLeave()',
    '(focusin)': 'rootProps.onFocusIn()',
    '(focusout)': 'rootProps.onFocusOut()',
  },
  providers: [{ provide: CAROUSEL, useExisting: CarouselRoot }],
})
export class CarouselRoot implements OnInit {
  private readonly host = inject(ElementRef<HTMLElement>)
  private readonly injector = inject(Injector)

  @Input({ required: true }) slides: string[] = []
  @Input({ required: true }) label = ''
  @Input() index?: number
  @Input() initialIndex?: number
  @Input() loop = false
  @Input() autoPlay = false
  @Input() autoPlayInterval?: number
  @Output() slideChange = new EventEmitter<number>()

  private readonly onSlideChange = injectStableCallback(
    () => (next: number) => this.slideChange.emit(next),
  )

  machine!: CarouselMachine
  readonly current = signal(0)

  ngOnInit(): void {
    const getSlideCount = () => this.slides.length
    const getLabel = () => this.label
    const getIndex = () => this.index
    const getLoop = () => this.loop
    const getAutoPlay = () => this.autoPlay
    const getAutoPlayInterval = () => this.autoPlayInterval
    this.machine = runInInjectionContext(this.injector, () =>
      injectMachine(() =>
        createCarousel({
          get slideCount() {
            return getSlideCount()
          },
          get label() {
            return getLabel()
          },
          get index() {
            return getIndex()
          },
          initialIndex: this.initialIndex,
          get loop() {
            return getLoop()
          },
          get autoPlay() {
            return getAutoPlay()
          },
          get autoPlayInterval() {
            return getAutoPlayInterval()
          },
          onSlideChange: this.onSlideChange,
        }),
      ),
    )
    this.machine.setRootEl(this.host.nativeElement)
    this.sync()
    this.machine.subscribe(() => this.sync())
  }

  get rootProps() {
    return this.machine.getRootProps()
  }

  private sync(): void {
    this.current.set(this.machine.state.currentIndex)
  }
}
