// packages/react/src/tier3/Drawer.tsx
import React, {
  createContext,
  useContext,
  useEffect,
  useId,
  useReducer,
  useRef,
  useState,
} from 'react'
import { createPortal } from 'react-dom'
import {
  createDrawer,
  type Drawer as DrawerMachine,
  type DrawerSide,
} from '@web-loom/foolscap-core'
import { useCallbackRef } from '../utils/useCallbackRef'
import { cx } from '../utils/cx'

export type { DrawerSide }

interface DrawerContextValue {
  close: () => void
  registerTitleId: (id: string | undefined) => void
}

const DrawerContext = createContext<DrawerContextValue | null>(null)

function useDrawerContext(): DrawerContextValue {
  const ctx = useContext(DrawerContext)
  if (!ctx) throw new Error('Drawer slot components must be used inside <Drawer>')
  return ctx
}

export interface DrawerProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  side?: DrawerSide
  size?: 'sm' | 'md' | 'lg'
  closeOnOverlayClick?: boolean
  closeOnEscape?: boolean
  animationDuration?: number
  className?: string
  children: React.ReactNode
}

export function Drawer({
  open,
  onOpenChange,
  side = 'right',
  size,
  closeOnOverlayClick = true,
  closeOnEscape = true,
  animationDuration = 250,
  className,
  children,
}: DrawerProps) {
  const panelRef = useRef<HTMLDialogElement>(null)
  const machineRef = useRef<DrawerMachine | null>(null)
  const [, forceUpdate] = useReducer((x: number) => x + 1, 0)
  const [labelledBy, setLabelledBy] = useState<string | undefined>()

  const stableOnOpenChange = useCallbackRef(onOpenChange)

  useEffect(() => {
    const el = panelRef.current
    if (!el) return

    const machine = createDrawer(el, {
      side,
      closeOnOverlayClick,
      closeOnEscape,
      animationDuration,
      onClose: () => stableOnOpenChange(false),
    })
    machineRef.current = machine
    const unsubscribe = machine.subscribe(() => forceUpdate())

    return () => {
      unsubscribe()
      machine.destroy()
      machineRef.current = null
    }
  }, [])

  useEffect(() => {
    const machine = machineRef.current
    if (!machine) return
    if (open) machine.open()
    else machine.close()
  }, [open])

  const state = machineRef.current?.state ?? { status: 'closed' as const, side }
  const panelProps = machineRef.current?.getPanelProps()
  const overlayProps = machineRef.current?.getOverlayProps()

  return createPortal(
    <div
      className={cx('fc-drawer', className)}
      data-state={state.status}
      data-side={side}
      data-size={size}
    >
      <div
        className="fc-drawer__overlay"
        aria-hidden="true"
        onClick={overlayProps?.onClick}
      />
      <dialog
        ref={panelRef}
        className="fc-drawer__panel"
        aria-modal={true}
        aria-labelledby={labelledBy}
        onTransitionEnd={(e) => {
          if (e.target === panelRef.current) {
            panelProps?.onTransitionEnd(e.propertyName)
          }
        }}
      >
        <DrawerContext.Provider
          value={{
            close: () => machineRef.current?.close(),
            registerTitleId: setLabelledBy,
          }}
        >
          {children}
        </DrawerContext.Provider>
      </dialog>
    </div>,
    document.body
  )
}

export interface DrawerHeaderProps extends React.HTMLAttributes<HTMLDivElement> {
  className?: string
  children: React.ReactNode
}

export function DrawerHeader({ className, children, ...props }: DrawerHeaderProps) {
  return (
    <div className={cx('fc-drawer__header', className)} {...props}>
      {children}
    </div>
  )
}

export interface DrawerTitleProps extends React.HTMLAttributes<HTMLHeadingElement> {
  className?: string
  children: React.ReactNode
}

export function DrawerTitle({ className, children, id, ...props }: DrawerTitleProps) {
  const reactId = useId().replace(/:/g, '')
  const generatedId = id ?? `fc-drawer-title-${reactId}`
  const { registerTitleId } = useDrawerContext()

  useEffect(() => {
    registerTitleId(generatedId)
    return () => registerTitleId(undefined)
  }, [generatedId, registerTitleId])

  return (
    <h2 id={generatedId} className={cx('fc-drawer__title', className)} {...props}>
      {children}
    </h2>
  )
}

export interface DrawerCloseProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  className?: string
  children?: React.ReactNode
}

export function DrawerClose({ className, children, onClick, ...props }: DrawerCloseProps) {
  const { close } = useDrawerContext()
  return (
    <button
      type="button"
      aria-label="Close drawer"
      className={cx('fc-drawer__close', className)}
      onClick={(e) => {
        close()
        onClick?.(e)
      }}
      {...props}
    >
      {children ?? '✕'}
    </button>
  )
}

export interface DrawerBodyProps extends React.HTMLAttributes<HTMLDivElement> {
  className?: string
  children: React.ReactNode
}

export function DrawerBody({ className, children, ...props }: DrawerBodyProps) {
  return (
    <div className={cx('fc-drawer__body', className)} {...props}>
      {children}
    </div>
  )
}

export interface DrawerFooterProps extends React.HTMLAttributes<HTMLDivElement> {
  className?: string
  children: React.ReactNode
}

export function DrawerFooter({ className, children, ...props }: DrawerFooterProps) {
  return (
    <div className={cx('fc-drawer__footer', className)} {...props}>
      {children}
    </div>
  )
}

// packages/angular/src/tier3/Drawer.ts
import {
  type AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  ElementRef,
  EventEmitter,
  inject,
  InjectionToken,
  Input,
  type OnChanges,
  Output,
  signal,
  type SimpleChanges,
  ViewChild,
} from '@angular/core'
import { createDrawer, type Drawer as DrawerMachine, type DrawerSide } from '@web-loom/foolscap-core'
import { injectStableCallback } from '../bindings/inject-stable-callback'
import { nextId } from '../utils/ids'
import { attachToBody } from '../utils/portal'

export type { DrawerSide }

export const DRAWER = new InjectionToken<Drawer>('fc-drawer')

function injectDrawer(): Drawer {
  const ctx = inject(DRAWER, { optional: true })
  if (!ctx) throw new Error('Drawer slot components must be used inside <Drawer>')
  return ctx
}

export interface DrawerProps {
  open: boolean
  side?: DrawerSide
  size?: 'sm' | 'md' | 'lg'
  closeOnOverlayClick?: boolean
  closeOnEscape?: boolean
  animationDuration?: number
}

export interface DrawerTitleProps {
  id?: string
}

@Component({
  selector: 'fc-drawer',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="fc-drawer__overlay" aria-hidden="true" (click)="onOverlayClick()"></div>
    <dialog
      #panel
      class="fc-drawer__panel"
      [attr.aria-modal]="true"
      [attr.aria-labelledby]="labelledBy()"
      (transitionend)="onTransitionEnd($event)"
    >
      <ng-content />
    </dialog>
  `,
  host: {
    class: 'fc-drawer',
    '[attr.data-state]': 'status()',
    '[attr.data-side]': 'side',
    '[attr.data-size]': 'size',
  },
  providers: [{ provide: DRAWER, useExisting: Drawer }],
})
export class Drawer implements AfterViewInit, OnChanges {
  @ViewChild('panel') private panel?: ElementRef<HTMLDialogElement>

  @Input({ required: true }) open = false
  @Input() side: DrawerSide = 'right'
  @Input() size?: DrawerProps['size']
  @Input() closeOnOverlayClick = true
  @Input() closeOnEscape = true
  @Input() animationDuration = 250
  @Output() openChange = new EventEmitter<boolean>()

  private machine: DrawerMachine | null = null
  private unsubscribe?: () => void
  private readonly onClose = injectStableCallback(() => () => this.openChange.emit(false))

  readonly labelledBy = signal<string | undefined>(undefined)
  readonly status = signal<'closed' | 'opening' | 'open' | 'closing'>('closed')

  constructor() {
    attachToBody(inject(ElementRef<HTMLElement>).nativeElement)
    inject(DestroyRef).onDestroy(() => {
      this.unsubscribe?.()
      this.machine?.destroy()
      this.machine = null
    })
  }

  ngAfterViewInit(): void {
    const el = this.panel?.nativeElement
    if (!el) return
    const instance = createDrawer(el, {
      side: this.side,
      closeOnOverlayClick: this.closeOnOverlayClick,
      closeOnEscape: this.closeOnEscape,
      animationDuration: this.animationDuration,
      onClose: this.onClose,
    })
    this.machine = instance
    this.unsubscribe = instance.subscribe(() => this.syncStatus())
    if (this.open) instance.open()
    this.syncStatus()
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (!changes['open'] || !this.machine) return
    if (this.open) this.machine.open()
    else this.machine.close()
    this.syncStatus()
  }

  registerTitleId(id?: string): void {
    this.labelledBy.set(id)
  }

  requestClose(): void {
    this.machine?.close()
  }

  onOverlayClick(): void {
    this.machine?.getOverlayProps().onClick()
  }

  onTransitionEnd(event: TransitionEvent): void {
    if (event.target !== this.panel?.nativeElement) return
    this.machine?.getPanelProps().onTransitionEnd(event.propertyName)
    this.syncStatus()
  }

  private syncStatus(): void {
    this.status.set(this.machine?.state.status ?? 'closed')
  }
}

@Component({
  selector: '[fc-drawer-header]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-drawer__header',
  },
})
export class DrawerHeader {
  readonly kind = 'header'
}

@Component({
  selector: 'h2[fc-drawer-title]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-drawer__title',
    '[attr.id]': 'titleId',
  },
})
export class DrawerTitle {
  private readonly ctx = injectDrawer()
  private readonly generatedId = nextId('fc-drawer-title')

  @Input() id?: string

  get titleId(): string {
    return this.id ?? this.generatedId
  }

  constructor() {
    this.ctx.registerTitleId(this.titleId)
    inject(DestroyRef).onDestroy(() => this.ctx.registerTitleId(undefined))
  }
}

@Component({
  selector: 'button[fc-drawer-close]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-drawer__close',
    '[attr.type]': '"button"',
    '[attr.aria-label]': 'ariaLabel ?? "Close drawer"',
    '(click)': 'onClick()',
  },
})
export class DrawerClose {
  private readonly ctx = injectDrawer()

  @Input('aria-label') ariaLabel?: string

  onClick(): void {
    this.ctx.requestClose()
  }
}

@Component({
  selector: '[fc-drawer-body]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-drawer__body',
  },
})
export class DrawerBody {
  readonly kind = 'body'
}

@Component({
  selector: '[fc-drawer-footer]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-drawer__footer',
  },
})
export class DrawerFooter {
  readonly kind = 'footer'
}
