// packages/react/src/tier3/Navigation.tsx
import React, { createContext, useCallback, useContext, useRef } from 'react'
import {
  createNavigation,
  type Navigation as NavigationMachine,
  type NavigationItem,
} from '@web-loom/foolscap-core'
import { useMachine } from '../hooks/useMachine'
import { useCallbackRef } from '../utils/useCallbackRef'
import { cx } from '../utils/cx'

interface NavigationContextValue {
  machine: NavigationMachine
  items: NavigationItem[]
  injectRootEl: (el: HTMLElement | null) => void
  injectTriggerEl: (index: number, el: HTMLButtonElement | null) => void
  injectSubmenuLinkEl: (parentIndex: number, childIndex: number, el: HTMLAnchorElement | null) => void
}

const NavigationContext = createContext<NavigationContextValue | null>(null)

function useNavigationContext(): NavigationContextValue {
  const ctx = useContext(NavigationContext)
  if (!ctx) throw new Error('Navigation components must be used inside NavigationRoot')
  return ctx
}

export type { NavigationItem }

export interface NavigationRootProps
  extends Omit<React.HTMLAttributes<HTMLElement>, 'children' | 'aria-label' | 'onToggle'>,
    React.RefAttributes<HTMLElement> {
  items: NavigationItem[]
  label?: string
  orientation?: 'horizontal' | 'vertical'
  onToggle?: (detail: { index: number | null; isOpen: boolean }) => void
  onMobileToggle?: (detail: { isExpanded: boolean }) => void
  className?: string
  children?: React.ReactNode
}

export function NavigationRoot({
  items,
  label = 'Main navigation',
  orientation = 'horizontal',
  onToggle,
  onMobileToggle,
  className,
  children,
  ref,
  ...props
}: NavigationRootProps) {
  const itemsRef = useRef(items)
  itemsRef.current = items
  const labelRef = useRef(label)
  labelRef.current = label
  const orientationRef = useRef(orientation)
  orientationRef.current = orientation
  const stableOnToggle = useCallbackRef(onToggle)
  const stableOnMobileToggle = useCallbackRef(onMobileToggle)

  const machine = useMachine(() =>
    createNavigation({
      get items() {
        return itemsRef.current
      },
      get label() {
        return labelRef.current
      },
      get orientation() {
        return orientationRef.current
      },
      onToggle: stableOnToggle,
      onMobileToggle: stableOnMobileToggle,
    })
  )

  const injectRootEl = useCallback((el: HTMLElement | null) => machine.setRootEl(el), [machine])
  const injectTriggerEl = useCallback(
    (index: number, el: HTMLButtonElement | null) => machine.setTriggerEl(index, el),
    [machine]
  )
  const injectSubmenuLinkEl = useCallback(
    (parentIndex: number, childIndex: number, el: HTMLAnchorElement | null) =>
      machine.setSubmenuLinkEl(parentIndex, childIndex, el),
    [machine]
  )
  const rootProps = machine.getRootProps()

  return (
    <NavigationContext.Provider
      value={{ machine, items, injectRootEl, injectTriggerEl, injectSubmenuLinkEl }}
    >
      <nav
        {...props}
        aria-label={rootProps['aria-label']}
        data-state={rootProps['data-state']}
        data-orientation={rootProps['data-orientation']}
        ref={(el) => {
          injectRootEl(el)
          if (typeof ref === 'function') ref(el)
          else if (ref) (ref as React.MutableRefObject<HTMLElement | null>).current = el
        }}
        className={cx('fc-navigation', className)}
      >
        {children ?? (
          <>
            <NavigationToggle />
            <NavigationList />
          </>
        )}
      </nav>
    </NavigationContext.Provider>
  )
}

export interface NavigationToggleProps
  extends Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, 'type'>,
    React.RefAttributes<HTMLButtonElement> {
  className?: string
}

export function NavigationToggle({ className, ref, children, onClick, onKeyDown, ...props }: NavigationToggleProps) {
  const { machine } = useNavigationContext()
  const toggleProps = machine.getToggleProps()

  return (
    <button
      type={toggleProps.type}
      {...props}
      aria-expanded={toggleProps['aria-expanded']}
      aria-controls={toggleProps['aria-controls']}
      aria-label={props['aria-label'] ?? toggleProps['aria-label']}
      onClick={(e) => {
        onClick?.(e)
        if (!e.defaultPrevented) toggleProps.onClick()
      }}
      onKeyDown={(e) => {
        onKeyDown?.(e)
        if (!e.defaultPrevented) toggleProps.onKeyDown(e.nativeEvent)
      }}
      ref={ref}
      className={cx('fc-navigation__toggle', className)}
    >
      {children ?? <span className="fc-navigation__icon" aria-hidden="true">☰</span>}
    </button>
  )
}

export interface NavigationListProps
  extends React.HTMLAttributes<HTMLUListElement>,
    React.RefAttributes<HTMLUListElement> {
  className?: string
}

export function NavigationList({ className, ref, ...props }: NavigationListProps) {
  const { machine, items, injectTriggerEl, injectSubmenuLinkEl } = useNavigationContext()
  const listProps = machine.getListProps()

  return (
    <ul
      {...props}
      id={listProps.id}
      hidden={listProps.hidden ? true : undefined}
      ref={ref}
      className={cx('fc-navigation__list', className)}
    >
      {items.map((item, index) => (
        <NavigationItemView
          key={`${item.label}-${item.href ?? index}`}
          item={item}
          index={index}
          machine={machine}
          injectTriggerEl={injectTriggerEl}
          injectSubmenuLinkEl={injectSubmenuLinkEl}
        />
      ))}
    </ul>
  )
}

interface NavigationItemViewProps {
  item: NavigationItem
  index: number
  machine: NavigationMachine
  injectTriggerEl: (index: number, el: HTMLButtonElement | null) => void
  injectSubmenuLinkEl: (parentIndex: number, childIndex: number, el: HTMLAnchorElement | null) => void
}

function NavigationItemView({
  item,
  index,
  machine,
  injectTriggerEl,
  injectSubmenuLinkEl,
}: NavigationItemViewProps) {
  const itemProps = machine.getItemProps(index)

  return (
    <li className="fc-navigation__item" data-state={itemProps['data-state']}>
      {item.children?.length ? (
        <>
          <NavigationTriggerView
            item={item}
            index={index}
            machine={machine}
            injectTriggerEl={injectTriggerEl}
          />
          <NavigationSubmenuView
            item={item}
            index={index}
            machine={machine}
            injectSubmenuLinkEl={injectSubmenuLinkEl}
          />
        </>
      ) : (
        <NavigationLinkView item={item} index={index} machine={machine} />
      )}
    </li>
  )
}

function NavigationLinkView({
  item,
  index,
  machine,
}: {
  item: NavigationItem
  index: number
  machine: NavigationMachine
}) {
  const linkProps = machine.getLinkProps(index)
  return (
    <a className="fc-navigation__link" href={linkProps.href} aria-current={linkProps['aria-current']}>
      {item.label}
    </a>
  )
}

function NavigationTriggerView({
  item,
  index,
  machine,
  injectTriggerEl,
}: {
  item: NavigationItem
  index: number
  machine: NavigationMachine
  injectTriggerEl: (index: number, el: HTMLButtonElement | null) => void
}) {
  const triggerProps = machine.getTriggerProps(index)
  return (
    <button
      type={triggerProps.type}
      aria-expanded={triggerProps['aria-expanded']}
      aria-controls={triggerProps['aria-controls']}
      onClick={triggerProps.onClick}
      onKeyDown={(e) => triggerProps.onKeyDown(e.nativeEvent)}
      ref={(el) => injectTriggerEl(index, el)}
      className="fc-navigation__trigger"
    >
      {item.label}
      <span className="fc-navigation__trigger-icon" aria-hidden="true">▾</span>
    </button>
  )
}

function NavigationSubmenuView({
  item,
  index,
  machine,
  injectSubmenuLinkEl,
}: {
  item: NavigationItem
  index: number
  machine: NavigationMachine
  injectSubmenuLinkEl: (parentIndex: number, childIndex: number, el: HTMLAnchorElement | null) => void
}) {
  const submenuProps = machine.getSubmenuProps(index)
  return (
    <ul
      id={submenuProps.id}
      hidden={submenuProps.hidden}
      onKeyDown={(e) => submenuProps.onKeyDown(e.nativeEvent)}
      className="fc-navigation__submenu"
    >
      {item.children?.map((child, childIndex) => {
        const linkProps = machine.getSubmenuLinkProps(index, childIndex)
        return (
          <li className="fc-navigation__submenu-item" key={`${child.label}-${child.href}`}>
            <a
              href={linkProps.href}
              aria-current={linkProps['aria-current']}
              onKeyDown={(e) => linkProps.onKeyDown(e.nativeEvent)}
              ref={(el) => injectSubmenuLinkEl(index, childIndex, el)}
              className="fc-navigation__submenu-link"
            >
              {child.label}
            </a>
          </li>
        )
      })}
    </ul>
  )
}

// packages/angular/src/tier3/Navigation.ts
import {
  afterNextRender,
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  EventEmitter,
  inject,
  InjectionToken,
  Injector,
  Input,
  type OnInit,
  Output,
  runInInjectionContext,
  signal,
} from '@angular/core'
import {
  createNavigation,
  type Navigation as NavigationMachine,
  type NavigationItem,
} from '@web-loom/foolscap-core'
import { injectMachine } from '../bindings/inject-machine'
import { injectStableCallback } from '../bindings/inject-stable-callback'

export type { NavigationItem }

export const NAVIGATION = new InjectionToken<NavigationRoot>('fc-navigation')

function injectNavigation(): NavigationRoot {
  const ctx = inject(NAVIGATION, { optional: true })
  if (!ctx) throw new Error('Navigation components must be used inside NavigationRoot')
  return ctx
}

export interface NavigationRootProps {
  items: NavigationItem[]
  label?: string
  orientation?: 'horizontal' | 'vertical'
}

@Component({
  selector: 'button[fc-navigation-toggle]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<span class="fc-navigation__icon" aria-hidden="true">☰</span>`,
  host: {
    class: 'fc-navigation__toggle',
    '[attr.type]': 'toggleProps.type',
    '[attr.aria-expanded]': 'toggleProps["aria-expanded"]',
    '[attr.aria-controls]': 'toggleProps["aria-controls"]',
    '[attr.aria-label]': 'ariaLabel ?? toggleProps["aria-label"]',
    '(click)': 'toggleProps.onClick()',
    '(keydown)': 'toggleProps.onKeyDown($event)',
  },
})
export class NavigationToggle {
  private readonly ctx = injectNavigation()

  @Input('aria-label') ariaLabel?: string

  get toggleProps() {
    return this.ctx.machine.getToggleProps()
  }
}

@Component({
  selector: 'ul[fc-navigation-list]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @for (item of ctx.items; track $index; let parentIndex = $index) {
      <li class="fc-navigation__item" [attr.data-state]="itemProps(parentIndex)['data-state']">
        @if (item.children?.length) {
          <button
            type="button"
            class="fc-navigation__trigger"
            [attr.aria-expanded]="triggerProps(parentIndex)['aria-expanded']"
            [attr.aria-controls]="triggerProps(parentIndex)['aria-controls']"
            (click)="triggerProps(parentIndex).onClick()"
            (keydown)="triggerProps(parentIndex).onKeyDown($event)"
          >
            {{ item.label }}
            <span class="fc-navigation__trigger-icon" aria-hidden="true">▾</span>
          </button>
          <ul
            class="fc-navigation__submenu"
            [attr.id]="submenuProps(parentIndex).id"
            [attr.hidden]="submenuProps(parentIndex).hidden ? '' : null"
            (keydown)="submenuProps(parentIndex).onKeyDown($event)"
          >
            @for (child of item.children; track child.href; let childIndex = $index) {
              <li class="fc-navigation__submenu-item">
                <a
                  class="fc-navigation__submenu-link"
                  [href]="submenuLinkProps(parentIndex, childIndex).href"
                  [attr.aria-current]="submenuLinkProps(parentIndex, childIndex)['aria-current']"
                  (keydown)="submenuLinkProps(parentIndex, childIndex).onKeyDown($event)"
                >
                  {{ child.label }}
                </a>
              </li>
            }
          </ul>
        } @else {
          <a
            class="fc-navigation__link"
            [href]="linkProps(parentIndex).href"
            [attr.aria-current]="linkProps(parentIndex)['aria-current']"
          >
            {{ item.label }}
          </a>
        }
      </li>
    }
  `,
  host: {
    class: 'fc-navigation__list',
    '[attr.id]': 'listProps.id',
    '[attr.hidden]': 'listProps.hidden ? "" : null',
  },
})
export class NavigationList {
  readonly ctx = injectNavigation()
  private readonly el = inject(ElementRef<HTMLUListElement>)

  constructor() {
    afterNextRender(() => {
      const items = this.el.nativeElement.querySelectorAll(':scope > .fc-navigation__item')
      items.forEach((li: Element, index: number) => {
        const btn = li.querySelector('.fc-navigation__trigger')
        this.ctx.machine.setTriggerEl(index, btn instanceof HTMLButtonElement ? btn : null)
        li.querySelectorAll('.fc-navigation__submenu-link').forEach((anchor: Element, childIndex: number) => {
          this.ctx.machine.setSubmenuLinkEl(
            index,
            childIndex,
            anchor instanceof HTMLAnchorElement ? anchor : null,
          )
        })
      })
    })
  }

  get listProps() {
    return this.ctx.machine.getListProps()
  }

  itemProps(index: number) {
    return this.ctx.machine.getItemProps(index)
  }

  linkProps(index: number) {
    return this.ctx.machine.getLinkProps(index)
  }

  triggerProps(index: number) {
    return this.ctx.machine.getTriggerProps(index)
  }

  submenuProps(index: number) {
    return this.ctx.machine.getSubmenuProps(index)
  }

  submenuLinkProps(parentIndex: number, childIndex: number) {
    return this.ctx.machine.getSubmenuLinkProps(parentIndex, childIndex)
  }
}

@Component({
  selector: 'nav[fc-navigation], fc-navigation',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NavigationToggle, NavigationList],
  template: `
    <button fc-navigation-toggle></button>
    <ul fc-navigation-list></ul>
  `,
  host: {
    class: 'fc-navigation',
    '[attr.aria-label]': 'label',
    '[attr.data-state]': 'expanded() ? "expanded" : "collapsed"',
    '[attr.data-orientation]': 'orientation',
    '[attr.role]': '"navigation"',
  },
  providers: [{ provide: NAVIGATION, useExisting: NavigationRoot }],
})
export class NavigationRoot implements OnInit {
  private readonly host = inject(ElementRef<HTMLElement>)
  private readonly injector = inject(Injector)

  @Input({ required: true }) items: NavigationItem[] = []
  @Input() label = 'Main navigation'
  @Input() orientation: NonNullable<NavigationRootProps['orientation']> = 'horizontal'
  @Output() toggle = new EventEmitter<{ index: number | null; isOpen: boolean }>()
  @Output() mobileToggle = new EventEmitter<{ isExpanded: boolean }>()

  private readonly onToggle = injectStableCallback(
    () => (detail: { index: number | null; isOpen: boolean }) => this.toggle.emit(detail),
  )
  private readonly onMobileToggle = injectStableCallback(
    () => (detail: { isExpanded: boolean }) => this.mobileToggle.emit(detail),
  )

  machine!: NavigationMachine
  readonly expanded = signal(false)

  ngOnInit(): void {
    const getItems = () => this.items
    const getLabel = () => this.label
    const getOrientation = () => this.orientation
    this.machine = runInInjectionContext(this.injector, () =>
      injectMachine(() =>
        createNavigation({
          get items() {
            return getItems()
          },
          get label() {
            return getLabel()
          },
          get orientation() {
            return getOrientation()
          },
          onToggle: this.onToggle,
          onMobileToggle: this.onMobileToggle,
        }),
      ),
    )
    this.machine.setRootEl(this.host.nativeElement)
    this.sync()
    this.machine.subscribe(() => this.sync())
  }

  private sync(): void {
    this.expanded.set(this.machine.getRootProps()['data-state'] === 'expanded')
  }
}
