// packages/react/src/tier3/Select.tsx
import React, { createContext, useCallback, useContext, useRef } from 'react'
import { createSelect, type Select as SelectMachine, type SelectOption } from '@web-loom/foolscap-core'
import { useMachine } from '../hooks/useMachine'
import { useCallbackRef } from '../utils/useCallbackRef'
import { cx } from '../utils/cx'

// ─── Context ──────────────────────────────────────────────────────────────────

interface SelectContextValue {
  machine: SelectMachine
  options: SelectOption[]
  placeholder: string
  injectTriggerEl: (el: HTMLButtonElement | null) => void
  injectListboxEl: (el: HTMLDivElement | null) => void
}

const SelectContext = createContext<SelectContextValue | null>(null)

function useSelectContext(): SelectContextValue {
  const ctx = useContext(SelectContext)
  if (!ctx) throw new Error('SelectTrigger and SelectListbox must be used inside SelectRoot')
  return ctx
}

// ─── Root ──────────────────────────────────────────────────────────────────────

export interface SelectRootProps {
  options: SelectOption[]
  value?: string
  defaultValue?: string
  onValueChange?: (value: string) => void
  onOpenChange?: (open: boolean) => void
  placeholder?: string
  placement?: 'bottom-start' | 'bottom-end' | 'top-start' | 'top-end'
  disabled?: boolean
  /** Adds a visually-hidden native <select> for form submission. */
  name?: string
  size?: 'sm' | 'md' | 'lg'
  className?: string
  children: React.ReactNode
}

export function SelectRoot({
  options,
  value,
  defaultValue,
  onValueChange,
  onOpenChange,
  placeholder = '',
  placement,
  disabled,
  name,
  size,
  className,
  children,
}: SelectRootProps) {
  // Keep mutable opts in refs so the machine always reads the latest values
  // without needing to be recreated on every render.
  const optionsRef = useRef(options)
  optionsRef.current = options
  const valueRef = useRef(value)
  valueRef.current = value
  const placementRef = useRef(placement)
  placementRef.current = placement
  // defaultValue intentionally not updated — snapshot at creation only
  const defaultValueRef = useRef(defaultValue)

  const stableOnValueChange = useCallbackRef(onValueChange)
  const stableOnOpenChange = useCallbackRef(onOpenChange)

  // Machine is created synchronously (useMachine), so DOM ref injections that
  // fire in the same commit phase will already find machineRef populated.
  const machine = useMachine(() =>
    createSelect({
      // Getters allow the machine to always read fresh values via closure
      // without needing explicit updates or machine recreation.
      get options() {
        return optionsRef.current
      },
      get value() {
        return valueRef.current
      },
      defaultValue: defaultValueRef.current,
      onValueChange: stableOnValueChange,
      onOpenChange: stableOnOpenChange,
      get placement() {
        return placementRef.current
      },
    })
  )

  const injectTriggerEl = useCallback(
    (el: HTMLButtonElement | null) => machine.setTriggerEl(el),
    [machine]
  )
  const injectListboxEl = useCallback(
    (el: HTMLDivElement | null) => machine.setListboxEl(el),
    [machine]
  )

  const state = machine.state

  return (
    <SelectContext.Provider value={{ machine, options, placeholder, injectTriggerEl, injectListboxEl }}>
      <div
        className={cx('fc-select', className)}
        data-state={state.open ? 'open' : 'closed'}
        data-size={size}
        data-disabled={disabled ? '' : undefined}
      >
        {name && (
          <select
            className="fc-select__native"
            name={name}
            aria-hidden="true"
            tabIndex={-1}
            value={state.value}
            onChange={() => {/* value synced by machine */}}
          >
            <option value="" />
            {options.map((opt) => (
              <option key={opt.value} value={opt.value} disabled={opt.disabled}>
                {opt.label}
              </option>
            ))}
          </select>
        )}
        {children}
      </div>
    </SelectContext.Provider>
  )
}

// ─── Trigger ───────────────────────────────────────────────────────────────────

export interface SelectTriggerProps
  extends Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, 'role'>,
    React.RefAttributes<HTMLButtonElement> {
  placeholder?: string
  className?: string
}

export function SelectTrigger({
  className,
  ref,
  placeholder: localPlaceholder,
  disabled,
  ...props
}: SelectTriggerProps) {
  const { machine, options, placeholder, injectTriggerEl } = useSelectContext()
  const triggerProps = machine.getTriggerProps()
  const state = machine.state

  const selectedLabel = options.find((o) => o.value === state.value)?.label
  const effectivePlaceholder = localPlaceholder ?? placeholder
  const displayText = selectedLabel ?? effectivePlaceholder
  const isEmpty = !selectedLabel

  // Destructure machine props individually to bridge DOM ↔ React event types.
  const {
    role,
    tabIndex,
    'aria-expanded': ariaExpanded,
    'aria-haspopup': ariaHaspopup,
    'aria-controls': ariaControls,
    'aria-activedescendant': ariaActivedescendant,
    onClick: machineClick,
    onKeyDown: machineKeyDown,
  } = triggerProps

  return (
    <button
      type="button"
      disabled={disabled}
      {...props}
      role={role}
      tabIndex={tabIndex}
      aria-expanded={ariaExpanded}
      aria-haspopup={ariaHaspopup}
      aria-controls={ariaControls}
      aria-activedescendant={ariaActivedescendant}
      onClick={machineClick}
      onKeyDown={(e) => machineKeyDown(e.nativeEvent)}
      ref={(el) => {
        injectTriggerEl(el)
        if (typeof ref === 'function') ref(el)
        else if (ref) (ref as React.MutableRefObject<HTMLButtonElement | null>).current = el
      }}
      className={cx('fc-select__trigger', className)}
    >
      <span
        className={cx(
          'fc-select__trigger-value',
          isEmpty && 'fc-select__trigger-value--placeholder'
        )}
      >
        {displayText}
      </span>
      <span className="fc-select__trigger-icon" aria-hidden="true">
        ▾
      </span>
    </button>
  )
}

// ─── Listbox ───────────────────────────────────────────────────────────────────

export interface SelectListboxProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, 'role'>,
    React.RefAttributes<HTMLDivElement> {
  className?: string
}

export function SelectListbox({
  className,
  ref,
  style,
  'aria-label': ariaLabel,
  ...props
}: SelectListboxProps) {
  const { machine, options, injectListboxEl } = useSelectContext()
  const listboxProps = machine.getListboxProps()
  const state = machine.state

  // Strip display from user styles — machine owns style.display via inline assignment
  // (same pattern as PopoverContent; see feedback_machine_visibility memory).
  const { display: _display, ...safeStyle } = (style ?? {}) as React.CSSProperties & {
    display?: string
  }

  // Destructure to bridge DOM ↔ React event types for onKeyDown.
  const {
    id: listboxId,
    role: listboxRole,
    hidden,
    onKeyDown: listboxKeyDown,
  } = listboxProps

  return (
    <div
      {...props}
      id={listboxId}
      role={listboxRole}
      hidden={hidden}
      onKeyDown={(e) => listboxKeyDown(e.nativeEvent)}
      ref={(el) => {
        injectListboxEl(el)
        if (typeof ref === 'function') ref(el)
        else if (ref) (ref as React.MutableRefObject<HTMLDivElement | null>).current = el
      }}
      style={safeStyle}
      aria-label={ariaLabel ?? listboxProps['aria-label']}
      className={cx('fc-select__listbox', className)}
    >
      {options.map((opt, index) => {
        const {
          id: optId,
          role: optRole,
          'aria-selected': ariaSelected,
          'aria-disabled': ariaDisabled,
          'data-highlighted': dataHighlighted,
          onClick: optClick,
          onMouseMove: optMouseMove,
        } = machine.getOptionProps(opt.value, index)
        return (
          <div
            key={opt.value}
            id={optId}
            role={optRole}
            aria-selected={ariaSelected}
            aria-disabled={ariaDisabled}
            // Present attribute = highlighted; absent = not highlighted (CSS [data-highlighted])
            data-highlighted={dataHighlighted ? '' : undefined}
            data-value={opt.value}
            onClick={optClick}
            onMouseMove={optMouseMove}
            className={cx('fc-select__option')}
          >
            <span className="fc-select__option-label">{opt.label}</span>
            <span className="fc-select__option-check" aria-hidden="true">
              {state.value === opt.value ? '✓' : ''}
            </span>
          </div>
        )
      })}
    </div>
  )
}

// packages/angular/src/tier3/Select.ts
import {
  type AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  EventEmitter,
  inject,
  InjectionToken,
  Injector,
  Input,
  type OnChanges,
  type OnInit,
  Output,
  runInInjectionContext,
  signal,
} from '@angular/core'
import { createSelect, type Select as SelectMachine, type SelectOption } from '@web-loom/foolscap-core'
import { injectMachine } from '../bindings/inject-machine'
import { injectStableCallback } from '../bindings/inject-stable-callback'
import { attachToBody } from '../utils/portal'

export type { SelectOption }

export const SELECT = new InjectionToken<SelectRoot>('fc-select')

export interface SelectRootProps {
  options: SelectOption[]
  value?: string
  defaultValue?: string
  placeholder?: string
  placement?: 'bottom-start' | 'bottom-end' | 'top-start' | 'top-end'
  disabled?: boolean
  name?: string
  size?: 'sm' | 'md' | 'lg'
}

export interface SelectTriggerProps {
  placeholder?: string
  disabled?: boolean
}

@Component({
  selector: 'fc-select',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (name) {
      <select class="fc-select__native" [attr.name]="name" aria-hidden="true" tabindex="-1">
        <option value=""></option>
        @for (opt of options; track opt.value) {
          <option [value]="opt.value" [disabled]="!!opt.disabled" [selected]="opt.value === selectedValue">
            {{ opt.label }}
          </option>
        }
      </select>
    }
    <ng-content />
  `,
  host: {
    class: 'fc-select',
    '[attr.data-state]': 'isOpen() ? "open" : "closed"',
    '[attr.data-size]': 'size',
    '[attr.data-disabled]': 'disabled ? "" : null',
  },
  providers: [{ provide: SELECT, useExisting: SelectRoot }],
})
export class SelectRoot implements OnInit, OnChanges {
  @Input({ required: true }) options: SelectOption[] = []
  @Input() value?: string
  @Input() defaultValue?: string
  @Input() placeholder = ''
  @Input() placement?: SelectRootProps['placement']
  @Input() disabled = false
  @Input() name?: string
  @Input() size?: SelectRootProps['size']
  @Output() valueChange = new EventEmitter<string>()
  @Output() openChange = new EventEmitter<boolean>()

  private readonly injector = inject(Injector)
  private readonly onValueChange = injectStableCallback(
    () => (value: string) => this.valueChange.emit(value),
  )
  private readonly onOpenChange = injectStableCallback(
    () => (open: boolean) => this.openChange.emit(open),
  )

  machine!: SelectMachine
  readonly isOpen = signal(false)
  readonly selectedValueState = signal('')

  ngOnInit(): void {
    const getOptions = () => this.options
    const getValue = () => this.value
    const getPlacement = () => this.placement
    this.machine = runInInjectionContext(this.injector, () =>
      injectMachine(() =>
        createSelect({
          get options() {
            return getOptions()
          },
          get value() {
            return getValue()
          },
          defaultValue: this.defaultValue,
          onValueChange: this.onValueChange,
          onOpenChange: this.onOpenChange,
          get placement() {
            return getPlacement()
          },
        }),
      ),
    )
    this.syncState()
    this.machine.subscribe(() => this.syncState())
  }

  ngOnChanges(): void {
    if (this.machine) this.syncState()
  }

  get selectedValue(): string {
    return this.selectedValueState()
  }

  setTriggerEl(el: HTMLElement | null): void {
    this.machine.setTriggerEl(el)
  }

  setListboxEl(el: HTMLElement | null): void {
    this.machine.setListboxEl(el)
  }

  private syncState(): void {
    this.isOpen.set(this.machine.state.open)
    this.selectedValueState.set(this.value !== undefined ? this.value : this.machine.state.value)
  }
}

function injectSelect(): SelectRoot {
  const ctx = inject(SELECT, { optional: true })
  if (!ctx) throw new Error('SelectTrigger and SelectListbox must be used inside SelectRoot')
  return ctx
}

@Component({
  selector: 'button[fc-select-trigger]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <span class="fc-select__trigger-value" [class.fc-select__trigger-value--placeholder]="isEmpty">
      {{ displayText }}
    </span>
    <span class="fc-select__trigger-icon" aria-hidden="true">▾</span>
  `,
  host: {
    class: 'fc-select__trigger',
    '[attr.type]': '"button"',
    '[disabled]': 'disabled',
    '[attr.role]': 'triggerProps.role',
    '[attr.tabindex]': 'triggerProps.tabIndex',
    '[attr.aria-expanded]': 'triggerProps["aria-expanded"]',
    '[attr.aria-haspopup]': 'triggerProps["aria-haspopup"]',
    '[attr.aria-controls]': 'triggerProps["aria-controls"]',
    '[attr.aria-activedescendant]': 'triggerProps["aria-activedescendant"]',
    '(click)': 'triggerProps.onClick()',
    '(keydown)': 'triggerProps.onKeyDown($event)',
  },
})
export class SelectTrigger implements AfterViewInit {
  private readonly el = inject(ElementRef<HTMLButtonElement>)
  protected readonly ctx = injectSelect()

  @Input() placeholder?: string
  @Input() disabled = false

  ngAfterViewInit(): void {
    this.ctx.setTriggerEl(this.el.nativeElement)
  }

  get triggerProps() {
    return this.ctx.machine.getTriggerProps()
  }

  get selectedLabel(): string | undefined {
    return this.ctx.options.find((opt) => opt.value === this.ctx.selectedValue)?.label
  }

  get isEmpty(): boolean {
    return !this.selectedLabel
  }

  get displayText(): string {
    return this.selectedLabel ?? this.placeholder ?? this.ctx.placeholder
  }
}

@Component({
  selector: 'div[fc-select-listbox]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @for (opt of ctx.options; track opt.value; let index = $index) {
      <div
        class="fc-select__option"
        [attr.id]="optionProps(opt.value, index).id"
        [attr.role]="optionProps(opt.value, index).role"
        [attr.aria-selected]="optionProps(opt.value, index)['aria-selected']"
        [attr.aria-disabled]="optionProps(opt.value, index)['aria-disabled']"
        [attr.data-highlighted]="optionProps(opt.value, index)['data-highlighted'] ? '' : null"
        [attr.data-value]="opt.value"
        (click)="optionProps(opt.value, index).onClick()"
        (mousemove)="optionProps(opt.value, index).onMouseMove()"
      >
        <span class="fc-select__option-label">{{ opt.label }}</span>
        <span class="fc-select__option-check" aria-hidden="true">{{
          ctx.selectedValue === opt.value ? '✓' : ''
        }}</span>
      </div>
    }
  `,
  host: {
    class: 'fc-select__listbox',
    '[attr.id]': 'listboxProps.id',
    '[attr.role]': 'listboxProps.role',
    '[attr.hidden]': 'listboxProps.hidden ? "" : null',
    '[attr.aria-label]': 'listboxProps["aria-label"]',
    '(keydown)': 'listboxProps.onKeyDown($event)',
  },
})
export class SelectListbox implements AfterViewInit {
  private readonly el = inject(ElementRef<HTMLElement>)
  protected readonly ctx = injectSelect()

  constructor() {
    attachToBody(this.el.nativeElement)
  }

  ngAfterViewInit(): void {
    this.ctx.setListboxEl(this.el.nativeElement)
  }

  get listboxProps() {
    return this.ctx.machine.getListboxProps()
  }

  optionProps(value: string, index: number) {
    return this.ctx.machine.getOptionProps(value, index)
  }
}
