// packages/react/src/tier3/Stepper.tsx
import React, { createContext, useCallback, useContext, useRef } from 'react'
import { createStepper, type Stepper as StepperMachine } from '@web-loom/foolscap-core'
import { useMachine } from '../hooks/useMachine'
import { useCallbackRef } from '../utils/useCallbackRef'
import { cx } from '../utils/cx'

interface StepperContextValue {
  machine: StepperMachine
  injectRootEl: (el: HTMLDivElement | null) => void
}

const StepperContext = createContext<StepperContextValue | null>(null)

function useStepperContext(): StepperContextValue {
  const ctx = useContext(StepperContext)
  if (!ctx) throw new Error('Stepper components must be used inside StepperRoot')
  return ctx
}

export interface StepperRootProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, 'children' | 'onChange'>,
    React.RefAttributes<HTMLDivElement> {
  label: string
  min?: number
  max?: number
  step?: number
  largeStep?: number
  value?: number
  defaultValue?: number
  name?: string
  disabled?: boolean
  editable?: boolean
  size?: 'sm' | 'md' | 'lg'
  formatValue?: (value: number) => string
  onValueChange?: (value: number, prevValue: number) => void
  className?: string
  children?: React.ReactNode
}

export function StepperRoot({
  label,
  min,
  max,
  step,
  largeStep,
  value,
  defaultValue,
  name,
  disabled,
  editable,
  size,
  formatValue,
  onValueChange,
  className,
  children,
  ref,
  ...props
}: StepperRootProps) {
  const minRef = useRef(min)
  minRef.current = min
  const maxRef = useRef(max)
  maxRef.current = max
  const stepRef = useRef(step)
  stepRef.current = step
  const largeStepRef = useRef(largeStep)
  largeStepRef.current = largeStep
  const valueRef = useRef(value)
  valueRef.current = value
  const defaultValueRef = useRef(defaultValue)
  const nameRef = useRef(name)
  nameRef.current = name
  const disabledRef = useRef(disabled)
  disabledRef.current = disabled
  const editableRef = useRef(editable)
  editableRef.current = editable
  const formatValueRef = useRef(formatValue)
  formatValueRef.current = formatValue
  const stableOnValueChange = useCallbackRef(onValueChange)

  const machine = useMachine(() =>
    createStepper({
      get min() {
        return minRef.current
      },
      get max() {
        return maxRef.current
      },
      get step() {
        return stepRef.current
      },
      get largeStep() {
        return largeStepRef.current
      },
      get value() {
        return valueRef.current
      },
      defaultValue: defaultValueRef.current,
      get name() {
        return nameRef.current
      },
      get disabled() {
        return disabledRef.current
      },
      get editable() {
        return editableRef.current
      },
      get formatValue() {
        return formatValueRef.current
      },
      onValueChange: stableOnValueChange,
    })
  )

  const injectRootEl = useCallback((el: HTMLDivElement | null) => machine.setRootEl(el), [machine])
  const rootProps = machine.getRootProps()

  return (
    <StepperContext.Provider value={{ machine, injectRootEl }}>
      <div
        {...props}
        role={rootProps.role}
        aria-labelledby={rootProps['aria-labelledby']}
        data-state={rootProps['data-state']}
        data-size={size}
        ref={(el) => {
          injectRootEl(el)
          if (typeof ref === 'function') ref(el)
          else if (ref) (ref as React.MutableRefObject<HTMLDivElement | null>).current = el
        }}
        className={cx('fc-stepper', className)}
      >
        {children ?? (
          <>
            <StepperLabel>{label}</StepperLabel>
            <div className="fc-stepper__controls">
              <StepperDecrement />
              <StepperInput />
              <StepperIncrement />
            </div>
            <StepperHiddenInput />
          </>
        )}
      </div>
    </StepperContext.Provider>
  )
}

export interface StepperLabelProps extends React.LabelHTMLAttributes<HTMLLabelElement> {
  className?: string
}

export function StepperLabel({ className, ...props }: StepperLabelProps) {
  const { machine } = useStepperContext()
  const labelProps = machine.getLabelProps()
  return (
    <label
      {...props}
      id={props.id ?? labelProps.id}
      htmlFor={props.htmlFor ?? labelProps.htmlFor}
      className={cx('fc-stepper__label', className)}
    />
  )
}

export interface StepperButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  className?: string
}

export function StepperDecrement({ className, children, ...props }: StepperButtonProps) {
  const { machine } = useStepperContext()
  const decrementProps = machine.getDecrementProps()
  return (
    <button
      {...props}
      type={decrementProps.type}
      aria-label={props['aria-label'] ?? decrementProps['aria-label']}
      aria-controls={decrementProps['aria-controls']}
      aria-disabled={decrementProps['aria-disabled']}
      disabled={props.disabled ?? decrementProps.disabled}
      onClick={decrementProps.onClick}
      onPointerDown={decrementProps.onPointerDown}
      onPointerUp={decrementProps.onPointerUp}
      onPointerCancel={decrementProps.onPointerCancel}
      onKeyUp={decrementProps.onKeyUp}
      className={cx('fc-stepper__decrement', className)}
    >
      {children ?? '−'}
    </button>
  )
}

export interface StepperInputProps extends React.HTMLAttributes<HTMLDivElement> {
  className?: string
}

export function StepperInput({ className, ...props }: StepperInputProps) {
  const { machine } = useStepperContext()
  const inputProps = machine.getInputProps()
  return (
    <div
      {...props}
      id={props.id ?? inputProps.id}
      role={inputProps.role}
      tabIndex={inputProps.tabIndex}
      aria-labelledby={inputProps['aria-labelledby']}
      aria-valuemin={inputProps['aria-valuemin']}
      aria-valuemax={inputProps['aria-valuemax']}
      aria-valuenow={inputProps['aria-valuenow']}
      aria-valuetext={inputProps['aria-valuetext']}
      aria-disabled={inputProps['aria-disabled']}
      contentEditable={inputProps.contentEditable}
      suppressContentEditableWarning={inputProps.suppressContentEditableWarning}
      onKeyDown={(e) => inputProps.onKeyDown(e.nativeEvent)}
      onInput={(e) => inputProps.onInput(e.currentTarget.textContent ?? '')}
      onBlur={(e) => inputProps.onBlur(e.currentTarget.textContent ?? '')}
      className={cx('fc-stepper__input', className)}
    >
      {inputProps.children}
    </div>
  )
}

export function StepperIncrement({ className, children, ...props }: StepperButtonProps) {
  const { machine } = useStepperContext()
  const incrementProps = machine.getIncrementProps()
  return (
    <button
      {...props}
      type={incrementProps.type}
      aria-label={props['aria-label'] ?? incrementProps['aria-label']}
      aria-controls={incrementProps['aria-controls']}
      aria-disabled={incrementProps['aria-disabled']}
      disabled={props.disabled ?? incrementProps.disabled}
      onClick={incrementProps.onClick}
      onPointerDown={incrementProps.onPointerDown}
      onPointerUp={incrementProps.onPointerUp}
      onPointerCancel={incrementProps.onPointerCancel}
      onKeyUp={incrementProps.onKeyUp}
      className={cx('fc-stepper__increment', className)}
    >
      {children ?? '+'}
    </button>
  )
}

export interface StepperHiddenInputProps extends React.InputHTMLAttributes<HTMLInputElement> {
  className?: string
}

export function StepperHiddenInput({ className, ...props }: StepperHiddenInputProps) {
  const { machine } = useStepperContext()
  const inputProps = machine.getHiddenInputProps()
  if (!inputProps.name && !props.name) return null
  return (
    <input
      {...props}
      type={inputProps.type}
      name={props.name ?? inputProps.name}
      value={inputProps.value}
      readOnly
      className={cx('fc-stepper__hidden-input', className)}
    />
  )
}

// packages/angular/src/tier3/Stepper.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  EventEmitter,
  inject,
  InjectionToken,
  Injector,
  Input,
  type OnInit,
  Output,
  runInInjectionContext,
  signal,
} from '@angular/core'
import { createStepper, type Stepper as StepperMachine } from '@web-loom/foolscap-core'
import { injectMachine } from '../bindings/inject-machine'
import { injectStableCallback } from '../bindings/inject-stable-callback'

export const STEPPER = new InjectionToken<StepperRoot>('fc-stepper')

function injectStepper(): StepperRoot {
  const ctx = inject(STEPPER, { optional: true })
  if (!ctx) throw new Error('Stepper components must be used inside StepperRoot')
  return ctx
}

export interface StepperRootProps {
  label: string
  min?: number
  max?: number
  step?: number
  largeStep?: number
  value?: number
  defaultValue?: number
  name?: string
  disabled?: boolean
  editable?: boolean
  size?: 'sm' | 'md' | 'lg'
  formatValue?: (value: number) => string
}

@Component({
  selector: 'label[fc-stepper-label]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-stepper__label',
    '[attr.id]': 'labelProps.id',
    '[attr.for]': 'labelProps.htmlFor',
  },
})
export class StepperLabel {
  private readonly ctx = injectStepper()

  get labelProps() {
    return this.ctx.machine.getLabelProps()
  }
}

@Component({
  selector: 'button[fc-stepper-decrement]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-stepper__decrement',
    '[attr.type]': 'decrementProps.type',
    '[attr.aria-label]': 'ariaLabel ?? decrementProps["aria-label"]',
    '[attr.aria-controls]': 'decrementProps["aria-controls"]',
    '[attr.aria-disabled]': 'decrementProps["aria-disabled"]',
    '[disabled]': 'decrementProps.disabled',
    '(click)': 'decrementProps.onClick()',
    '(pointerdown)': 'decrementProps.onPointerDown()',
    '(pointerup)': 'decrementProps.onPointerUp()',
    '(pointercancel)': 'decrementProps.onPointerCancel()',
    '(keyup)': 'decrementProps.onKeyUp()',
  },
})
export class StepperDecrement {
  private readonly ctx = injectStepper()

  @Input('aria-label') ariaLabel?: string

  get decrementProps() {
    return this.ctx.machine.getDecrementProps()
  }
}

@Component({
  selector: 'button[fc-stepper-increment]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-stepper__increment',
    '[attr.type]': 'incrementProps.type',
    '[attr.aria-label]': 'ariaLabel ?? incrementProps["aria-label"]',
    '[attr.aria-controls]': 'incrementProps["aria-controls"]',
    '[attr.aria-disabled]': 'incrementProps["aria-disabled"]',
    '[disabled]': 'incrementProps.disabled',
    '(click)': 'incrementProps.onClick()',
    '(pointerdown)': 'incrementProps.onPointerDown()',
    '(pointerup)': 'incrementProps.onPointerUp()',
    '(pointercancel)': 'incrementProps.onPointerCancel()',
    '(keyup)': 'incrementProps.onKeyUp()',
  },
})
export class StepperIncrement {
  private readonly ctx = injectStepper()

  @Input('aria-label') ariaLabel?: string

  get incrementProps() {
    return this.ctx.machine.getIncrementProps()
  }
}

@Component({
  selector: '[fc-stepper-input]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `{{ inputProps.children }}`,
  host: {
    class: 'fc-stepper__input',
    '[attr.id]': 'inputProps.id',
    '[attr.role]': 'inputProps.role',
    '[attr.tabindex]': 'inputProps.tabIndex',
    '[attr.aria-labelledby]': 'inputProps["aria-labelledby"]',
    '[attr.aria-valuemin]': 'inputProps["aria-valuemin"]',
    '[attr.aria-valuemax]': 'inputProps["aria-valuemax"]',
    '[attr.aria-valuenow]': 'inputProps["aria-valuenow"]',
    '[attr.aria-valuetext]': 'inputProps["aria-valuetext"]',
    '[attr.aria-disabled]': 'inputProps["aria-disabled"]',
    '[attr.contenteditable]': 'inputProps.contentEditable',
    '(input)': 'onInput($event)',
    '(blur)': 'onBlur($event)',
    '(keydown)': 'onKeyDown($event)',
  },
})
export class StepperInput {
  private readonly ctx = injectStepper()

  get inputProps() {
    return this.ctx.machine.getInputProps()
  }

  onInput(event: Event): void {
    this.ctx.machine.getInputProps().onInput((event.currentTarget as HTMLElement).textContent ?? '')
  }

  onBlur(event: Event): void {
    this.ctx.machine.getInputProps().onBlur((event.currentTarget as HTMLElement).textContent ?? '')
  }

  onKeyDown(event: KeyboardEvent): void {
    this.ctx.machine.getInputProps().onKeyDown(event)
  }
}

@Component({
  selector: 'input[fc-stepper-hidden-input]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: ``,
  host: {
    class: 'fc-stepper__hidden-input',
    '[attr.type]': '"hidden"',
    '[attr.name]': 'hiddenProps.name',
    '[attr.value]': 'hiddenProps.value',
    '[attr.readonly]': 'true',
  },
})
export class StepperHiddenInput {
  private readonly ctx = injectStepper()

  get hiddenProps() {
    return this.ctx.machine.getHiddenInputProps()
  }
}

@Component({
  selector: 'fc-stepper',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [StepperLabel, StepperDecrement, StepperInput, StepperIncrement, StepperHiddenInput],
  template: `
    <label fc-stepper-label>{{ label }}</label>
    <div class="fc-stepper__controls">
      <button fc-stepper-decrement>−</button>
      <div fc-stepper-input></div>
      <button fc-stepper-increment>+</button>
    </div>
    @if (name) {
      <input fc-stepper-hidden-input />
    }
  `,
  host: {
    class: 'fc-stepper',
    '[attr.role]': 'rootProps.role',
    '[attr.aria-labelledby]': 'rootProps["aria-labelledby"]',
    '[attr.data-state]': 'rootProps["data-state"]',
    '[attr.data-size]': 'size',
  },
  providers: [{ provide: STEPPER, useExisting: StepperRoot }],
})
export class StepperRoot implements OnInit {
  private readonly host = inject(ElementRef<HTMLDivElement>)
  private readonly injector = inject(Injector)

  @Input({ required: true }) label = ''
  @Input() min?: number
  @Input() max?: number
  @Input() step?: number
  @Input() largeStep?: number
  @Input() value?: number
  @Input() defaultValue?: number
  @Input() name?: string
  @Input() disabled?: boolean
  @Input() editable?: boolean
  @Input() size?: StepperRootProps['size']
  @Input() formatValue?: (value: number) => string
  @Output() valueChange = new EventEmitter<number>()

  private readonly onValueChange = injectStableCallback(
    () => (value: number) => this.valueChange.emit(value),
  )

  machine!: StepperMachine
  readonly current = signal(0)

  ngOnInit(): void {
    const getMin = () => this.min
    const getMax = () => this.max
    const getStep = () => this.step
    const getLargeStep = () => this.largeStep
    const getValue = () => this.value
    const getName = () => this.name
    const getDisabled = () => this.disabled
    const getEditable = () => this.editable
    const getFormatValue = () => this.formatValue
    this.machine = runInInjectionContext(this.injector, () =>
      injectMachine(() =>
        createStepper({
          get min() {
            return getMin()
          },
          get max() {
            return getMax()
          },
          get step() {
            return getStep()
          },
          get largeStep() {
            return getLargeStep()
          },
          get value() {
            return getValue()
          },
          defaultValue: this.defaultValue,
          get name() {
            return getName()
          },
          get disabled() {
            return getDisabled()
          },
          get editable() {
            return getEditable()
          },
          get formatValue() {
            return getFormatValue()
          },
          onValueChange: this.onValueChange,
        }),
      ),
    )
    this.machine.setRootEl(this.host.nativeElement)
    this.sync()
    this.machine.subscribe(() => this.sync())
  }

  get rootProps() {
    return (
      this.machine?.getRootProps() ?? {
        role: 'group' as const,
        'aria-labelledby': undefined,
        'data-state': undefined,
      }
    )
  }

  private sync(): void {
    this.current.set(this.machine.state.value)
  }
}
