// packages/react/src/tier3/Tabs.tsx
import React, { createContext, useContext } from 'react'
import { createTabs, type Tabs } from '@web-loom/foolscap-core'
import { useMachine } from '../hooks/useMachine'
import { useCallbackRef } from '../utils/useCallbackRef'
import { cx } from '../utils/cx'

interface TabsContextValue {
  machine: Tabs
  currentValue: string
}

const TabsContext = createContext<TabsContextValue | null>(null)

function useTabsContext(): TabsContextValue {
  const ctx = useContext(TabsContext)
  if (!ctx) throw new Error('Tab/TabsList/TabPanel must be used inside TabsRoot')
  return ctx
}

export interface TabsRootProps {
  defaultValue?: string
  value?: string
  onValueChange?: (value: string) => void
  activationMode?: 'automatic' | 'manual'
  orientation?: 'horizontal' | 'vertical'
  variant?: 'underline' | 'contained'
  loop?: boolean
  className?: string
  children: React.ReactNode
}

export function TabsRoot({
  defaultValue,
  value,
  onValueChange,
  activationMode,
  orientation,
  loop,
  variant,
  className,
  children,
}: TabsRootProps) {
  const stableOnChange = useCallbackRef(onValueChange)
  const machine = useMachine(() =>
    createTabs({ defaultValue, value, activationMode, orientation, loop, onValueChange: stableOnChange }),
  )

  // In controlled mode options.value in the machine is stale after re-renders.
  // Always derive currentValue from the React prop so context consumers are correct.
  const currentValue = value !== undefined ? value : machine.state.value

  return (
    <TabsContext.Provider value={{ machine, currentValue }}>
      <div className={cx('fc-tabs', className)} data-variant={variant} data-orientation={orientation ?? 'horizontal'}>
        {children}
      </div>
    </TabsContext.Provider>
  )
}

export interface TabsListProps extends React.HTMLAttributes<HTMLDivElement> {
  className?: string
  children: React.ReactNode
}

export function TabsList({ className, children, ...props }: TabsListProps) {
  const { machine } = useTabsContext()
  const tablistProps = machine.getTablistProps()
  return (
    <div
      {...tablistProps}
      {...props}
      className={cx('fc-tabs__tablist', className)}
    >
      {children}
    </div>
  )
}

export interface TabProps {
  value: string
  disabled?: boolean
  className?: string
  children: React.ReactNode
}

export function Tab({ value, disabled, className, children }: TabProps) {
  const { machine, currentValue } = useTabsContext()
  const isSelected = currentValue === value
  // Spread machine props for id, aria-controls, onClick, onKeyDown
  // then override aria-selected and tabIndex using context-derived currentValue
  const { onClick, onKeyDown, id, 'aria-controls': ariaControls } = machine.getTabProps(value)

  return (
    <button
      type="button"
      role="tab"
      id={id}
      aria-controls={ariaControls}
      aria-selected={isSelected}
      tabIndex={isSelected ? 0 : -1}
      data-state={isSelected ? 'active' : 'inactive'}
      disabled={disabled}
      className={cx('fc-tabs__tab', className)}
      onClick={onClick}
      onKeyDown={onKeyDown as unknown as React.KeyboardEventHandler<HTMLButtonElement>}
    >
      {children}
    </button>
  )
}

export interface TabPanelProps {
  value: string
  className?: string
  children: React.ReactNode
}

export function TabPanel({ value, className, children }: TabPanelProps) {
  const { machine, currentValue } = useTabsContext()
  const { id, 'aria-labelledby': labelledBy } = machine.getPanelProps(value)

  return (
    <div
      role="tabpanel"
      id={id}
      aria-labelledby={labelledBy}
      hidden={currentValue !== value}
      className={cx('fc-tabs__panel', className)}
    >
      {children}
    </div>
  )
}

// packages/angular/src/tier3/Tabs.ts
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  inject,
  InjectionToken,
  Injector,
  Input,
  type OnChanges,
  type OnInit,
  Output,
  runInInjectionContext,
  signal,
} from '@angular/core'
import { createTabs, type Tabs } from '@web-loom/foolscap-core'
import { injectMachine } from '../bindings/inject-machine'
import { injectStableCallback } from '../bindings/inject-stable-callback'

export const TABS = new InjectionToken<TabsRoot>('fc-tabs')

export interface TabsRootProps {
  defaultValue?: string
  value?: string
  activationMode?: 'automatic' | 'manual'
  orientation?: 'horizontal' | 'vertical'
  variant?: 'underline' | 'contained'
  loop?: boolean
}

export interface TabProps {
  value: string
  disabled?: boolean
}

export interface TabPanelProps {
  value: string
}

@Component({
  selector: 'fc-tabs',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-tabs',
    '[attr.data-variant]': 'variant',
    '[attr.data-orientation]': 'orientation ?? "horizontal"',
  },
  providers: [{ provide: TABS, useExisting: TabsRoot }],
})
export class TabsRoot implements OnInit, OnChanges {
  @Input() defaultValue?: string
  @Input() value?: string
  @Input() activationMode?: TabsRootProps['activationMode']
  @Input() orientation?: TabsRootProps['orientation']
  @Input() variant?: TabsRootProps['variant']
  @Input() loop?: boolean
  @Output() valueChange = new EventEmitter<string>()

  private readonly injector = inject(Injector)
  private readonly onValueChange = injectStableCallback(
    () => (value: string) => this.valueChange.emit(value),
  )

  machine!: Tabs
  readonly valueState = signal('')

  ngOnInit(): void {
    const getValue = () => this.value
    this.machine = runInInjectionContext(this.injector, () =>
      injectMachine(() =>
        createTabs({
          defaultValue: this.defaultValue,
          get value() {
            return getValue()
          },
          activationMode: this.activationMode,
          orientation: this.orientation,
          loop: this.loop,
          onValueChange: this.onValueChange,
        }),
      ),
    )
    this.syncValue()
    this.machine.subscribe(() => this.syncValue())
  }

  ngOnChanges(): void {
    this.syncValue()
  }

  get selectedValue(): string {
    return this.valueState()
  }

  private syncValue(): void {
    if (this.value !== undefined) {
      this.valueState.set(this.value)
      return
    }
    if (!this.machine) return
    this.valueState.set(this.machine.state.value)
  }
}

function injectTabs(): TabsRoot {
  const ctx = inject(TABS, { optional: true })
  if (!ctx) throw new Error('Tab/TabsList/TabPanel must be used inside TabsRoot')
  return ctx
}

@Component({
  selector: '[fc-tabs-list]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-tabs__tablist',
    '[attr.role]': 'tablistProps.role',
    '[attr.aria-orientation]': 'tablistProps["aria-orientation"]',
  },
})
export class TabsList {
  private readonly ctx = injectTabs()

  get tablistProps() {
    return this.ctx.machine.getTablistProps()
  }
}

@Component({
  selector: 'button[fc-tab]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-tabs__tab',
    '[attr.type]': '"button"',
    '[attr.role]': '"tab"',
    '[attr.id]': 'tabProps.id',
    '[attr.aria-controls]': 'tabProps["aria-controls"]',
    '[attr.aria-selected]': 'isSelected',
    '[attr.tabindex]': 'isSelected ? 0 : -1',
    '[attr.data-state]': 'isSelected ? "active" : "inactive"',
    '[disabled]': 'disabled',
    '(click)': 'onClick()',
    '(keydown)': 'onKeyDown($event)',
  },
})
export class Tab {
  private readonly ctx = injectTabs()

  @Input({ required: true }) value!: string
  @Input() disabled = false

  get tabProps() {
    return this.ctx.machine.getTabProps(this.value)
  }

  get isSelected(): boolean {
    return this.ctx.selectedValue === this.value
  }

  onClick(): void {
    this.ctx.machine.getTabProps(this.value).onClick()
  }

  onKeyDown(event: KeyboardEvent): void {
    this.ctx.machine.getTabProps(this.value).onKeyDown(event)
  }
}

@Component({
  selector: '[fc-tab-panel]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-tabs__panel',
    '[attr.role]': '"tabpanel"',
    '[attr.id]': 'panelProps.id',
    '[attr.aria-labelledby]': 'panelProps["aria-labelledby"]',
    '[attr.hidden]': 'isHidden ? "" : null',
  },
})
export class TabPanel {
  private readonly ctx = injectTabs()

  @Input({ required: true }) value!: string

  get panelProps() {
    return this.ctx.machine.getPanelProps(this.value)
  }

  get isHidden(): boolean {
    return this.ctx.selectedValue !== this.value
  }
}
