// packages/react/src/tier1/ButtonGroup.tsx
import React from 'react'
import { cx } from '../utils/cx'

export interface ButtonGroupProps extends React.HTMLAttributes<HTMLDivElement>, React.RefAttributes<HTMLDivElement> {
  orientation?: 'horizontal' | 'vertical'
}

export function ButtonGroup({ orientation = 'horizontal', className, ref, ...props }: ButtonGroupProps) {
  return (
    <div
      {...props}
      ref={ref}
      role={props.role ?? 'group'}
      data-orientation={orientation === 'vertical' ? 'vertical' : undefined}
      className={cx('fc-button-group', className)}
    />
  )
}

// packages/angular/src/tier1/ButtonGroup.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'

export interface ButtonGroupProps {
  orientation?: 'horizontal' | 'vertical'
}

@Component({
  selector: 'fc-button-group',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-button-group',
    '[attr.role]': '"group"',
    '[attr.data-orientation]': 'orientation === "vertical" ? "vertical" : null',
  },
})
export class ButtonGroup {
  @Input() orientation: NonNullable<ButtonGroupProps['orientation']> = 'horizontal'
}
