// packages/react/src/tier1/Button.tsx
import React from 'react'
import { cx } from '../utils/cx'

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    React.RefAttributes<HTMLButtonElement> {
  variant?: 'primary' | 'secondary' | 'ghost' | 'danger'
  size?: 'sm' | 'md' | 'lg'
  loading?: boolean
  iconStart?: React.ReactNode
  iconEnd?: React.ReactNode
}

export function Button({
  variant = 'primary',
  size = 'md',
  loading,
  iconStart,
  iconEnd,
  className,
  children,
  ref,
  disabled,
  ...props
}: ButtonProps) {
  return (
    <button
      ref={ref}
      type="button"
      data-variant={variant}
      data-size={size}
      data-state={loading ? 'loading' : undefined}
      aria-disabled={loading || disabled || undefined}
      disabled={disabled}
      className={cx('fc-button', className)}
      {...props}
    >
      {iconStart && (
        <span className="fc-button__icon-start" aria-hidden="true">
          {iconStart}
        </span>
      )}
      <span className="fc-button__label">{children}</span>
      {iconEnd && (
        <span className="fc-button__icon-end" aria-hidden="true">
          {iconEnd}
        </span>
      )}
    </button>
  )
}

// packages/angular/src/tier1/Button.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'

export interface ButtonProps {
  variant?: 'primary' | 'secondary' | 'ghost' | 'danger'
  size?: 'sm' | 'md' | 'lg'
  loading?: boolean
  disabled?: boolean
}

@Component({
  selector: 'button[fc-button]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <span class="fc-button__icon-start" aria-hidden="true">
      <ng-content select="[fcIconStart]" />
    </span>
    <span class="fc-button__label">
      <ng-content />
    </span>
    <span class="fc-button__icon-end" aria-hidden="true">
      <ng-content select="[fcIconEnd]" />
    </span>
  `,
  host: {
    class: 'fc-button',
    '[attr.type]': 'type',
    '[attr.data-variant]': 'variant',
    '[attr.data-size]': 'size',
    '[attr.data-state]': 'loading ? "loading" : null',
    '[attr.aria-disabled]': 'loading || disabled ? true : null',
    '[disabled]': 'disabled',
  },
})
export class Button {
  @Input() variant: NonNullable<ButtonProps['variant']> = 'primary'
  @Input() size: NonNullable<ButtonProps['size']> = 'md'
  @Input() loading = false
  @Input() disabled = false
  @Input() type: 'button' | 'submit' | 'reset' = 'button'
}
