// packages/react/src/tier1/Card.tsx
import React from 'react'
import { cx } from '../utils/cx'

export interface CardProps extends React.HTMLAttributes<HTMLElement>, React.RefAttributes<HTMLElement> {
  variant?: 'default' | 'flat' | 'elevated'
  as?: 'article' | 'div' | 'section'
}

export function Card({ variant = 'default', as = 'article', className, ref, ...props }: CardProps) {
  return React.createElement(as, {
    ...props,
    ref,
    'data-variant': variant === 'default' ? undefined : variant,
    className: cx('fc-card', className),
  })
}

export interface CardSectionProps extends React.HTMLAttributes<HTMLDivElement>, React.RefAttributes<HTMLDivElement> {}

export function CardMedia({ className, ref, ...props }: CardSectionProps) {
  return <div {...props} ref={ref} className={cx('fc-card__media', className)} />
}

export function CardBody({ className, ref, ...props }: CardSectionProps) {
  return <div {...props} ref={ref} className={cx('fc-card__body', className)} />
}

export function CardTitle({ className, ref, ...props }: React.HTMLAttributes<HTMLHeadingElement> & React.RefAttributes<HTMLHeadingElement>) {
  return <h3 {...props} ref={ref} className={cx('fc-card__title', className)} />
}

export function CardDescription({ className, ref, ...props }: React.HTMLAttributes<HTMLParagraphElement> & React.RefAttributes<HTMLParagraphElement>) {
  return <p {...props} ref={ref} className={cx('fc-card__description', className)} />
}

export function CardFooter({ className, ref, ...props }: CardSectionProps) {
  return <div {...props} ref={ref} className={cx('fc-card__footer', className)} />
}

// packages/angular/src/tier1/Card.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'

export interface CardProps {
  variant?: 'default' | 'flat' | 'elevated'
  as?: 'article' | 'div' | 'section'
}

@Component({
  selector: 'fc-card, article[fc-card], div[fc-card], section[fc-card]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-card',
    '[attr.data-variant]': 'variant === "default" ? null : variant',
  },
})
export class Card {
  @Input() variant: NonNullable<CardProps['variant']> = 'default'
  @Input() as: NonNullable<CardProps['as']> = 'article'
}

@Component({
  selector: 'fc-card-media',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: { class: 'fc-card__media' },
})
export class CardMedia {}

@Component({
  selector: 'fc-card-body',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: { class: 'fc-card__body' },
})
export class CardBody {}

@Component({
  selector: 'h3[fc-card-title], fc-card-title',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: { class: 'fc-card__title' },
})
export class CardTitle {}

@Component({
  selector: 'p[fc-card-description], fc-card-description',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: { class: 'fc-card__description' },
})
export class CardDescription {}

@Component({
  selector: 'fc-card-footer',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: { class: 'fc-card__footer' },
})
export class CardFooter {}
