// packages/react/src/tier1/Footer.tsx
import React from 'react'
import { cx } from '../utils/cx'

export interface FooterProps extends React.HTMLAttributes<HTMLElement>, React.RefAttributes<HTMLElement> {}

export function Footer({ className, ref, ...props }: FooterProps) {
  return <footer {...props} ref={ref} className={cx('fc-footer', className)} />
}

export interface FooterSectionProps extends React.HTMLAttributes<HTMLDivElement>, React.RefAttributes<HTMLDivElement> {}

export function FooterGrid({ className, ref, ...props }: FooterSectionProps) {
  return <div {...props} ref={ref} className={cx('fc-footer__grid', className)} />
}

export function FooterSectionTitle({ className, ref, ...props }: React.HTMLAttributes<HTMLHeadingElement> & React.RefAttributes<HTMLHeadingElement>) {
  return <h2 {...props} ref={ref} className={cx('fc-footer__section-title', className)} />
}

export function FooterLinks({ className, ref, ...props }: React.HTMLAttributes<HTMLUListElement> & React.RefAttributes<HTMLUListElement>) {
  return <ul {...props} ref={ref} className={cx('fc-footer__links', className)} />
}

export function FooterBottom({ className, ref, ...props }: FooterSectionProps) {
  return <div {...props} ref={ref} className={cx('fc-footer__bottom', className)} />
}

// packages/angular/src/tier1/Footer.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'

@Component({
  selector: 'footer[fc-footer]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: { class: 'fc-footer' },
})
export class Footer {}

@Component({
  selector: 'fc-footer-grid',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: { class: 'fc-footer__grid' },
})
export class FooterGrid {}

@Component({
  selector: 'h2[fc-footer-section-title]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: { class: 'fc-footer__section-title' },
})
export class FooterSectionTitle {}

@Component({
  selector: 'ul[fc-footer-links]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: { class: 'fc-footer__links' },
})
export class FooterLinks {}

@Component({
  selector: 'fc-footer-bottom',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: { class: 'fc-footer__bottom' },
})
export class FooterBottom {}
