// packages/react/src/tier1/Image.tsx
import React from 'react'
import { cx } from '../utils/cx'

export interface ImageProps extends React.ImgHTMLAttributes<HTMLImageElement>, React.RefAttributes<HTMLImageElement> {
  variant?: 'default' | 'rounded' | 'circle' | 'bordered' | 'shadow'
}

export function Image({ variant = 'default', className, ref, ...props }: ImageProps) {
  return (
    <img
      {...props}
      ref={ref}
      data-variant={variant === 'default' ? undefined : variant}
      className={cx('fc-image', className)}
    />
  )
}

// packages/angular/src/tier1/Image.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'

export interface ImageProps {
  variant?: 'default' | 'rounded' | 'circle' | 'bordered' | 'shadow'
}

@Component({
  selector: 'img[fc-image]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '',
  host: {
    class: 'fc-image',
    '[attr.data-variant]': 'variant === "default" ? null : variant',
  },
})
export class Image {
  @Input() variant: NonNullable<ImageProps['variant']> = 'default'
}
