// packages/react/src/tier1/List.tsx
import React from 'react'
import { cx } from '../utils/cx'

export interface ListProps
  extends React.HTMLAttributes<HTMLUListElement | HTMLOListElement>,
    React.RefAttributes<HTMLUListElement | HTMLOListElement> {
  variant?: 'bulleted' | 'numbered' | 'plain'
}

export function List({ variant = 'bulleted', className, ref, ...props }: ListProps) {
  const Component = variant === 'numbered' ? 'ol' : 'ul'
  return (
    <Component
      {...props}
      ref={ref as React.Ref<HTMLOListElement & HTMLUListElement>}
      data-variant={variant}
      className={cx('fc-list', className)}
    />
  )
}

// packages/angular/src/tier1/List.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'

export interface ListProps {
  variant?: 'bulleted' | 'numbered' | 'plain'
}

@Component({
  selector: 'ul[fc-list], ol[fc-list]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-list',
    '[attr.data-variant]': 'variant',
  },
})
export class List {
  @Input() variant: NonNullable<ListProps['variant']> = 'bulleted'
}
