// packages/react/src/tier1/Spinner.tsx
import React from 'react'
import { cx } from '../utils/cx'

export interface SpinnerProps extends React.HTMLAttributes<HTMLSpanElement>, React.RefAttributes<HTMLSpanElement> {
  size?: 'sm' | 'md' | 'lg'
  label?: string
}

export function Spinner({ size = 'md', label = 'Loading', className, ref, ...props }: SpinnerProps) {
  return (
    <span
      {...props}
      ref={ref}
      role="status"
      data-size={size}
      aria-label={label}
      className={cx('fc-spinner', className)}
    />
  )
}

// packages/angular/src/tier1/Spinner.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'

export interface SpinnerProps {
  size?: 'sm' | 'md' | 'lg'
  label?: string
}

@Component({
  selector: 'fc-spinner, span[fc-spinner]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '',
  host: {
    class: 'fc-spinner',
    role: 'status',
    '[attr.data-size]': 'size',
    '[attr.aria-label]': 'label',
  },
})
export class Spinner {
  @Input() size: NonNullable<SpinnerProps['size']> = 'md'
  @Input() label = 'Loading'
}
