// packages/react/src/tier1/Stack.tsx
import React from 'react'
import { cx } from '../utils/cx'

export interface StackProps extends React.HTMLAttributes<HTMLDivElement>, React.RefAttributes<HTMLDivElement> {
  gap?: '1' | '2' | '3' | '4' | '6' | '8' | '12'
  align?: 'start' | 'center' | 'end' | 'stretch'
}

export function Stack({ gap = '4', align, className, ref, ...props }: StackProps) {
  return <div {...props} ref={ref} data-gap={gap} data-align={align} className={cx('fc-stack', className)} />
}

// packages/angular/src/tier1/Stack.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'

export interface StackProps {
  gap?: '1' | '2' | '3' | '4' | '6' | '8' | '12'
  align?: 'start' | 'center' | 'end' | 'stretch'
}

@Component({
  selector: 'fc-stack',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-stack',
    '[attr.data-gap]': 'gap',
    '[attr.data-align]': 'align',
  },
})
export class Stack {
  @Input() gap: NonNullable<StackProps['gap']> = '4'
  @Input() align?: StackProps['align']
}
