// packages/react/src/tier1/Table.tsx
import React from 'react'
import { cx } from '../utils/cx'

export interface TableProps extends React.TableHTMLAttributes<HTMLTableElement>, React.RefAttributes<HTMLTableElement> {
  variant?: 'default' | 'striped' | 'bordered'
}

export function Table({ variant = 'default', className, ref, ...props }: TableProps) {
  return (
    <table
      {...props}
      ref={ref}
      data-variant={variant === 'default' ? undefined : variant}
      className={cx('fc-table', className)}
    />
  )
}

// packages/angular/src/tier1/Table.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'

export interface TableProps {
  variant?: 'default' | 'striped' | 'bordered'
}

@Component({
  selector: 'table[fc-table]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-table',
    '[attr.data-variant]': 'variant === "default" ? null : variant',
  },
})
export class Table {
  @Input() variant: NonNullable<TableProps['variant']> = 'default'
}
