// packages/react/src/tier1/Textarea.tsx
import React from 'react'
import { cx } from '../utils/cx'

export interface TextareaProps
  extends React.TextareaHTMLAttributes<HTMLTextAreaElement>,
    React.RefAttributes<HTMLTextAreaElement> {
  invalid?: boolean
}

export function Textarea({ invalid, className, ref, ...props }: TextareaProps) {
  return (
    <textarea
      {...props}
      ref={ref}
      aria-invalid={invalid ? 'true' : props['aria-invalid']}
      data-state={invalid ? 'error' : undefined}
      className={cx('fc-textarea', className)}
    />
  )
}

// packages/angular/src/tier1/Textarea.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core'

export interface TextareaProps {
  invalid?: boolean
  value?: string
}

@Component({
  selector: 'textarea[fc-textarea]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '',
  host: {
    class: 'fc-textarea',
    '[attr.aria-invalid]': 'invalid ? "true" : null',
    '[attr.data-state]': 'invalid ? "error" : null',
    '(input)': 'onInput($event)',
  },
})
export class Textarea {
  @Input() invalid = false
  @Input() value?: string
  @Output() valueChange = new EventEmitter<string>()

  onInput(event: Event): void {
    this.valueChange.emit((event.target as HTMLTextAreaElement).value)
  }
}
