// packages/react/src/tier1/Video.tsx
import React from 'react'
import { cx } from '../utils/cx'

export interface VideoProps extends React.VideoHTMLAttributes<HTMLVideoElement>, React.RefAttributes<HTMLVideoElement> {
  variant?: 'default' | 'bordered'
}

export function Video({ variant = 'default', className, ref, ...props }: VideoProps) {
  return (
    <video
      {...props}
      ref={ref}
      data-variant={variant === 'default' ? undefined : variant}
      className={cx('fc-video', className)}
    />
  )
}

export interface VideoEmbedProps extends React.HTMLAttributes<HTMLDivElement>, React.RefAttributes<HTMLDivElement> {}

export function VideoEmbed({ className, ref, ...props }: VideoEmbedProps) {
  return <div {...props} ref={ref} className={cx('fc-video-embed', className)} />
}

// packages/angular/src/tier1/Video.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'

export interface VideoProps {
  variant?: 'default' | 'bordered'
}

@Component({
  selector: 'video[fc-video]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-video',
    '[attr.data-variant]': 'variant === "default" ? null : variant',
  },
})
export class Video {
  @Input() variant: NonNullable<VideoProps['variant']> = 'default'
}

@Component({
  selector: 'fc-video-embed',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-video-embed',
  },
})
export class VideoEmbed {}
