// packages/angular/src/tier1/Alert.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core'

export interface AlertProps {
  variant?: 'info' | 'success' | 'warning' | 'error'
  live?: 'assertive' | 'polite'
  title?: string
  description?: string
  dismissLabel?: string
}

@Component({
  selector: 'fc-alert',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <span class="fc-alert__icon" aria-hidden="true">
      <ng-content select="[fcIcon]" />
    </span>
    <div class="fc-alert__body">
      @if (title) {
        <p class="fc-alert__title">{{ title }}</p>
      }
      @if (description) {
        <p class="fc-alert__description">{{ description }}</p>
      }
      <ng-content />
    </div>
    @if (dismiss.observed) {
      <button
        class="fc-alert__dismiss"
        type="button"
        [attr.aria-label]="dismissLabel"
        (click)="dismiss.emit()"
      >
        x
      </button>
    }
  `,
  host: {
    class: 'fc-alert',
    '[attr.role]': 'live === "polite" ? "status" : "alert"',
    '[attr.data-variant]': 'variant',
    '[attr.data-live]': 'live',
  },
})
export class Alert {
  @Input() variant: NonNullable<AlertProps['variant']> = 'info'
  @Input() live: NonNullable<AlertProps['live']> = 'assertive'
  @Input() title?: string
  @Input() description?: string
  @Input() dismissLabel = 'Dismiss alert'
  @Output() dismiss = new EventEmitter<void>()
}

// packages/react/src/tier1/Alert.tsx
import React from 'react'
import { cx } from '../utils/cx'

export interface AlertProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, 'title'>,
    React.RefAttributes<HTMLDivElement> {
  variant?: 'info' | 'success' | 'warning' | 'error'
  live?: 'assertive' | 'polite'
  icon?: React.ReactNode
  title?: React.ReactNode
  description?: React.ReactNode
  dismissLabel?: string
  onDismiss?: () => void
}

export function Alert({
  variant = 'info',
  live = 'assertive',
  icon,
  title,
  description,
  dismissLabel = 'Dismiss alert',
  onDismiss,
  className,
  children,
  ref,
  role,
  ...props
}: AlertProps) {
  return (
    <div
      {...props}
      ref={ref}
      role={role ?? (live === 'polite' ? 'status' : 'alert')}
      data-variant={variant}
      data-live={live}
      className={cx('fc-alert', className)}
    >
      {icon && (
        <span className="fc-alert__icon" aria-hidden="true">
          {icon}
        </span>
      )}
      <div className="fc-alert__body">
        {title && <p className="fc-alert__title">{title}</p>}
        {description ? <p className="fc-alert__description">{description}</p> : children}
      </div>
      {onDismiss && (
        <button className="fc-alert__dismiss" type="button" aria-label={dismissLabel} onClick={onDismiss}>
          x
        </button>
      )}
    </div>
  )
}
