// packages/angular/src/tier1/Avatar.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'

export interface AvatarProps {
  src?: string
  alt?: string
  fallback?: string
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl'
}

@Component({
  selector: 'fc-avatar, span[fc-avatar]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (src) {
      <img [src]="src" [alt]="alt" />
    }
    {{ fallback }}
    <ng-content />
  `,
  host: {
    class: 'fc-avatar',
    '[attr.data-size]': 'size',
  },
})
export class Avatar {
  @Input() src?: string
  @Input() alt = ''
  @Input() fallback?: string
  @Input() size: NonNullable<AvatarProps['size']> = 'md'
}

@Component({
  selector: 'fc-avatar-group',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-avatar-group',
  },
})
export class AvatarGroup {}

// packages/react/src/tier1/Avatar.tsx
import React from 'react'
import { cx } from '../utils/cx'

export interface AvatarProps extends React.HTMLAttributes<HTMLSpanElement>, React.RefAttributes<HTMLSpanElement> {
  src?: string
  alt?: string
  fallback?: React.ReactNode
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl'
}

export function Avatar({
  src,
  alt = '',
  fallback,
  size = 'md',
  className,
  children,
  ref,
  ...props
}: AvatarProps) {
  return (
    <span {...props} ref={ref} data-size={size} className={cx('fc-avatar', className)}>
      {src && <img src={src} alt={alt} />}
      {fallback ?? children}
    </span>
  )
}

export interface AvatarGroupProps
  extends React.HTMLAttributes<HTMLDivElement>,
    React.RefAttributes<HTMLDivElement> {}

export function AvatarGroup({ className, ref, ...props }: AvatarGroupProps) {
  return <div {...props} ref={ref} className={cx('fc-avatar-group', className)} />
}
