// packages/angular/src/tier1/Badge.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'

export interface BadgeProps {
  variant?: 'default' | 'outline' | 'subtle'
}

@Component({
  selector: 'fc-badge, span[fc-badge]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-badge',
    '[attr.data-variant]': 'variant === "default" ? null : variant',
  },
})
export class Badge {
  @Input() variant: NonNullable<BadgeProps['variant']> = 'default'
}

// packages/react/src/tier1/Badge.tsx
import React from 'react'
import { cx } from '../utils/cx'

export interface BadgeProps extends React.HTMLAttributes<HTMLSpanElement>, React.RefAttributes<HTMLSpanElement> {
  variant?: 'default' | 'outline' | 'subtle'
}

export function Badge({ variant = 'default', className, ref, ...props }: BadgeProps) {
  return (
    <span
      {...props}
      ref={ref}
      data-variant={variant === 'default' ? undefined : variant}
      className={cx('fc-badge', className)}
    />
  )
}
