// packages/angular/src/tier1/Breadcrumbs.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'

export interface BreadcrumbsProps {
  label?: string
}

@Component({
  selector: 'fc-breadcrumbs, nav[fc-breadcrumbs]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <ol class="fc-breadcrumbs">
      <ng-content />
    </ol>
  `,
  host: {
    '[attr.aria-label]': 'label',
  },
})
export class Breadcrumbs {
  @Input() label = 'Breadcrumb'
}

@Component({
  selector: 'fc-breadcrumb-item, li[fc-breadcrumb-item]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
})
export class BreadcrumbItem {}

// packages/react/src/tier1/Breadcrumbs.tsx
import React from 'react'
import { cx } from '../utils/cx'

export interface BreadcrumbsProps
  extends React.OlHTMLAttributes<HTMLOListElement>,
    React.RefAttributes<HTMLOListElement> {
  label?: string
}

export function Breadcrumbs({ label = 'Breadcrumb', className, ref, ...props }: BreadcrumbsProps) {
  return (
    <nav aria-label={label}>
      <ol {...props} ref={ref} className={cx('fc-breadcrumbs', className)} />
    </nav>
  )
}

export interface BreadcrumbItemProps extends React.LiHTMLAttributes<HTMLLIElement>, React.RefAttributes<HTMLLIElement> {}

export function BreadcrumbItem({ ref, ...props }: BreadcrumbItemProps) {
  return <li {...props} ref={ref} />
}
