// packages/angular/src/tier1/ColorPicker.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core'
import { nextId } from '../utils/ids'

export interface ColorPickerProps {
  label?: string
  rootClassName?: string
  showValue?: boolean
  defaultValue?: string
  value?: string
}

@Component({
  selector: 'fc-color-picker',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (label) {
      <label class="fc-color-picker__label" [attr.for]="inputId">{{ label }}</label>
    }
    <span class="fc-color-picker__swatch" [style.backgroundColor]="displayValue">
      <input
        type="color"
        class="fc-color-picker__input"
        [id]="inputId"
        [value]="displayValue"
        (change)="onChange($event)"
      />
    </span>
    @if (showValue) {
      <span class="fc-color-picker__value">{{ displayValue }}</span>
    }
  `,
  host: {
    class: 'fc-color-picker',
  },
})
export class ColorPicker {
  @Input() label?: string
  @Input() rootClassName?: string
  @Input() showValue = true
  @Input() defaultValue = '#000000'
  @Input() value?: string
  @Input() id?: string
  @Output() valueChange = new EventEmitter<string>()

  private uncontrolled?: string
  readonly generatedId = nextId('fc-color')

  get inputId(): string {
    return this.id ?? this.generatedId
  }

  get displayValue(): string {
    return this.value ?? this.uncontrolled ?? this.defaultValue
  }

  onChange(event: Event): void {
    const next = (event.target as HTMLInputElement).value
    if (this.value === undefined) this.uncontrolled = next
    this.valueChange.emit(next)
  }
}

// packages/react/src/tier1/ColorPicker.tsx
import React, { useId, useState } from 'react'
import { cx } from '../utils/cx'

export interface ColorPickerProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'type'>,
    React.RefAttributes<HTMLInputElement> {
  label: React.ReactNode
  rootClassName?: string
  showValue?: boolean
}

export function ColorPicker({
  label,
  rootClassName,
  className,
  id,
  value,
  defaultValue = '#000000',
  showValue = true,
  onChange,
  ref,
  ...props
}: ColorPickerProps) {
  const generatedId = useId()
  const inputId = id ?? generatedId
  const [uncontrolledValue, setUncontrolledValue] = useState(String(defaultValue))
  const displayValue = String(value ?? uncontrolledValue)

  return (
    <div className={cx('fc-color-picker', rootClassName)}>
      <label className="fc-color-picker__label" htmlFor={inputId}>
        {label}
      </label>
      <span className="fc-color-picker__swatch" style={{ backgroundColor: displayValue }}>
        <input
          {...props}
          id={inputId}
          ref={ref}
          type="color"
          value={value}
          defaultValue={value == null ? defaultValue : undefined}
          onChange={(event) => {
            if (value == null) setUncontrolledValue(event.currentTarget.value)
            onChange?.(event)
          }}
          className={cx('fc-color-picker__input', className)}
        />
      </span>
      {showValue && <span className="fc-color-picker__value">{displayValue}</span>}
    </div>
  )
}
