// packages/angular/src/tier1/EmptyState.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'

export interface EmptyStateProps {
  title?: string
  description?: string
}

@Component({
  selector: 'fc-empty-state',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="fc-empty-state__icon">
      <ng-content select="[fcIcon]" />
    </div>
    @if (title) {
      <div class="fc-empty-state__title">{{ title }}</div>
    }
    @if (description) {
      <div class="fc-empty-state__description">{{ description }}</div>
    }
    <ng-content />
    <div class="fc-empty-state__action">
      <ng-content select="[fcAction]" />
    </div>
  `,
  host: {
    class: 'fc-empty-state',
  },
})
export class EmptyState {
  @Input() title?: string
  @Input() description?: string
}

// packages/react/src/tier1/EmptyState.tsx
import React from 'react'
import { cx } from '../utils/cx'

export interface EmptyStateProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, 'title'>,
    React.RefAttributes<HTMLDivElement> {
  icon?: React.ReactNode
  title?: React.ReactNode
  description?: React.ReactNode
  action?: React.ReactNode
}

export function EmptyState({ icon, title, description, action, className, children, ref, ...props }: EmptyStateProps) {
  return (
    <div {...props} ref={ref} className={cx('fc-empty-state', className)}>
      {icon && <div className="fc-empty-state__icon">{icon}</div>}
      {title && <div className="fc-empty-state__title">{title}</div>}
      {description && <div className="fc-empty-state__description">{description}</div>}
      {children}
      {action && <div className="fc-empty-state__action">{action}</div>}
    </div>
  )
}
