// packages/angular/src/tier1/Fieldset.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'

export interface FieldsetProps {
  legend?: string
  hint?: string
}

@Component({
  selector: 'fieldset[fc-fieldset]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (legend) {
      <legend class="fc-fieldset__legend">{{ legend }}</legend>
    }
    @if (hint) {
      <p class="fc-fieldset__hint">{{ hint }}</p>
    }
    <div class="fc-fieldset__body">
      <ng-content />
    </div>
  `,
  host: {
    class: 'fc-fieldset',
  },
})
export class Fieldset {
  @Input() legend?: string
  @Input() hint?: string
}

// packages/react/src/tier1/Fieldset.tsx
import React from 'react'
import { cx } from '../utils/cx'

export interface FieldsetProps
  extends React.FieldsetHTMLAttributes<HTMLFieldSetElement>,
    React.RefAttributes<HTMLFieldSetElement> {
  legend: React.ReactNode
  hint?: React.ReactNode
}

export function Fieldset({ legend, hint, className, children, ref, ...props }: FieldsetProps) {
  return (
    <fieldset {...props} ref={ref} className={cx('fc-fieldset', className)}>
      <legend className="fc-fieldset__legend">{legend}</legend>
      {hint && <p className="fc-fieldset__hint">{hint}</p>}
      <div className="fc-fieldset__body">{children}</div>
    </fieldset>
  )
}
