// packages/angular/src/tier1/File.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'
import { nextId } from '../utils/ids'

export interface FileProps {
  variant?: 'default' | 'dropzone'
  label?: string
  rootClassName?: string
}

@Component({
  selector: 'fc-file',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (label) {
      <label [attr.for]="inputId">{{ label }}</label>
    }
    <input type="file" class="fc-file__input" [id]="inputId" [class]="inputClass" />
    <ng-content />
  `,
  host: {
    class: 'fc-file',
    '[attr.data-variant]': 'variant === "default" ? null : variant',
  },
})
export class File {
  @Input() variant: NonNullable<FileProps['variant']> = 'default'
  @Input() label?: string
  @Input() rootClassName?: string
  @Input() id?: string
  @Input() inputClass?: string

  readonly generatedId = nextId('fc-file')

  get inputId(): string {
    return this.id ?? this.generatedId
  }
}

// packages/react/src/tier1/File.tsx
import React, { useId } from 'react'
import { cx } from '../utils/cx'

export interface FileProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'type'>,
    React.RefAttributes<HTMLInputElement> {
  variant?: 'default' | 'dropzone'
  label?: React.ReactNode
  rootClassName?: string
}

export function File({ variant = 'default', label, rootClassName, className, id, ref, ...props }: FileProps) {
  const generatedId = useId()
  const inputId = id ?? generatedId

  return (
    <div
      className={cx('fc-file', rootClassName)}
      data-variant={variant === 'default' ? undefined : variant}
    >
      {label && <label htmlFor={inputId}>{label}</label>}
      <input {...props} id={inputId} ref={ref} type="file" className={cx('fc-file__input', className)} />
    </div>
  )
}
