// packages/angular/src/tier1/Hero.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'

export interface HeroProps {
  variant?: 'default' | 'split'
}

@Component({
  selector: 'section[fc-hero], fc-hero',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-hero',
    '[attr.data-variant]': 'variant === "default" ? null : variant',
  },
})
export class Hero {
  @Input() variant: NonNullable<HeroProps['variant']> = 'default'
}

@Component({
  selector: 'p[fc-hero-eyebrow], fc-hero-eyebrow',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: { class: 'fc-hero__eyebrow' },
})
export class HeroEyebrow {}

@Component({
  selector: 'h1[fc-hero-title], fc-hero-title',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: { class: 'fc-hero__title' },
})
export class HeroTitle {}

@Component({
  selector: 'p[fc-hero-description], fc-hero-description',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: { class: 'fc-hero__description' },
})
export class HeroDescription {}

@Component({
  selector: 'fc-hero-actions',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: { class: 'fc-hero__actions' },
})
export class HeroActions {}

// packages/react/src/tier1/Hero.tsx
import React from 'react'
import { cx } from '../utils/cx'

export interface HeroProps extends React.HTMLAttributes<HTMLElement>, React.RefAttributes<HTMLElement> {
  variant?: 'default' | 'split'
}

export function Hero({ variant = 'default', className, ref, ...props }: HeroProps) {
  return (
    <section
      {...props}
      ref={ref}
      data-variant={variant === 'default' ? undefined : variant}
      className={cx('fc-hero', className)}
    />
  )
}

export function HeroEyebrow({ className, ref, ...props }: React.HTMLAttributes<HTMLParagraphElement> & React.RefAttributes<HTMLParagraphElement>) {
  return <p {...props} ref={ref} className={cx('fc-hero__eyebrow', className)} />
}

export function HeroTitle({ className, ref, ...props }: React.HTMLAttributes<HTMLHeadingElement> & React.RefAttributes<HTMLHeadingElement>) {
  return <h1 {...props} ref={ref} className={cx('fc-hero__title', className)} />
}

export function HeroDescription({ className, ref, ...props }: React.HTMLAttributes<HTMLParagraphElement> & React.RefAttributes<HTMLParagraphElement>) {
  return <p {...props} ref={ref} className={cx('fc-hero__description', className)} />
}

export function HeroActions({ className, ref, ...props }: React.HTMLAttributes<HTMLDivElement> & React.RefAttributes<HTMLDivElement>) {
  return <div {...props} ref={ref} className={cx('fc-hero__actions', className)} />
}
