// packages/angular/src/tier1/Quote.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'

export interface QuoteProps {
  variant?: 'default' | 'pull'
  citeText?: string
}

@Component({
  selector: 'blockquote[fc-quote], fc-quote',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <ng-content />
    @if (citeText) {
      <cite class="fc-quote__cite">{{ citeText }}</cite>
    }
  `,
  host: {
    class: 'fc-quote',
    '[attr.data-variant]': 'variant === "default" ? null : variant',
  },
})
export class Quote {
  @Input() variant: NonNullable<QuoteProps['variant']> = 'default'
  @Input() citeText?: string
}

// packages/react/src/tier1/Quote.tsx
import React from 'react'
import { cx } from '../utils/cx'

export interface QuoteProps
  extends React.BlockquoteHTMLAttributes<HTMLQuoteElement>,
    React.RefAttributes<HTMLQuoteElement> {
  variant?: 'default' | 'pull'
  citeText?: React.ReactNode
}

export function Quote({ variant = 'default', citeText, className, children, ref, ...props }: QuoteProps) {
  return (
    <blockquote
      {...props}
      ref={ref}
      data-variant={variant === 'default' ? undefined : variant}
      className={cx('fc-quote', className)}
    >
      {children}
      {citeText && <cite className="fc-quote__cite">{citeText}</cite>}
    </blockquote>
  )
}
