// packages/angular/src/tier1/RadioButton.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'
import { nextId } from '../utils/ids'

export interface RadioButtonProps {
  label?: string
  rootClassName?: string
}

@Component({
  selector: 'fc-radio-button',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <input
      type="radio"
      class="fc-radio-button__input"
      [id]="inputId"
      [class]="inputClass"
      [attr.name]="name"
      [attr.value]="value"
    />
    <span class="fc-radio-button__control" aria-hidden="true"></span>
    @if (label) {
      <label class="fc-radio-button__label" [attr.for]="inputId">{{ label }}</label>
    }
    <ng-content />
  `,
  host: {
    class: 'fc-radio-button',
    '[attr.id]': 'null',
  },
})
export class RadioButton {
  @Input() label?: string
  @Input() rootClassName?: string
  @Input() id?: string
  @Input() name?: string
  @Input() value?: string
  @Input() inputClass?: string

  readonly generatedId = nextId('fc-radio')

  get inputId(): string {
    return this.id ?? this.generatedId
  }
}

// packages/react/src/tier1/RadioButton.tsx
import React, { useId } from 'react'
import { cx } from '../utils/cx'

export interface RadioButtonProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'type'>,
    React.RefAttributes<HTMLInputElement> {
  label: React.ReactNode
  rootClassName?: string
}

export function RadioButton({ label, rootClassName, className, id, ref, ...props }: RadioButtonProps) {
  const generatedId = useId()
  const inputId = id ?? generatedId

  return (
    <div className={cx('fc-radio-button', rootClassName)}>
      <input {...props} id={inputId} ref={ref} type="radio" className={cx('fc-radio-button__input', className)} />
      <span className="fc-radio-button__control" aria-hidden="true" />
      <label className="fc-radio-button__label" htmlFor={inputId}>
        {label}
      </label>
    </div>
  )
}
