// packages/angular/src/tier1/Separator.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'

export interface SeparatorProps {
  orientation?: 'horizontal' | 'vertical'
  decorative?: boolean
}

@Component({
  selector: 'fc-separator',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '',
  host: {
    class: 'fc-separator',
    '[attr.role]': 'decorative ? "presentation" : "separator"',
    '[attr.aria-orientation]': 'decorative ? null : orientation',
    '[attr.data-orientation]': 'orientation === "vertical" ? "vertical" : null',
  },
})
export class Separator {
  @Input() orientation: NonNullable<SeparatorProps['orientation']> = 'horizontal'
  @Input() decorative = true
}

// packages/react/src/tier1/Separator.tsx
import React from 'react'
import { cx } from '../utils/cx'

export interface SeparatorProps extends React.HTMLAttributes<HTMLDivElement>, React.RefAttributes<HTMLDivElement> {
  orientation?: 'horizontal' | 'vertical'
  decorative?: boolean
}

export function Separator({
  orientation = 'horizontal',
  decorative = true,
  className,
  ref,
  ...props
}: SeparatorProps) {
  return (
    <div
      {...props}
      ref={ref}
      role={decorative ? 'presentation' : 'separator'}
      aria-orientation={decorative ? undefined : orientation}
      data-orientation={orientation === 'vertical' ? 'vertical' : undefined}
      className={cx('fc-separator', className)}
    />
  )
}
