// packages/angular/src/tier1/Skeleton.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'

export interface SkeletonProps {
  variant?: 'block' | 'text' | 'circle'
}

@Component({
  selector: 'fc-skeleton, span[fc-skeleton]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '',
  host: {
    class: 'fc-skeleton',
    '[attr.aria-hidden]': '"true"',
    '[attr.data-variant]': 'variant === "block" ? null : variant',
  },
})
export class Skeleton {
  @Input() variant: NonNullable<SkeletonProps['variant']> = 'block'
}

// packages/react/src/tier1/Skeleton.tsx
import React from 'react'
import { cx } from '../utils/cx'

export interface SkeletonProps extends React.HTMLAttributes<HTMLSpanElement>, React.RefAttributes<HTMLSpanElement> {
  variant?: 'block' | 'text' | 'circle'
}

export function Skeleton({ variant = 'block', className, ref, ...props }: SkeletonProps) {
  return (
    <span
      {...props}
      ref={ref}
      aria-hidden="true"
      data-variant={variant === 'block' ? undefined : variant}
      className={cx('fc-skeleton', className)}
    />
  )
}
