// packages/angular/src/tier1/TextInput.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core'

export interface TextInputProps {
  size?: 'sm' | 'md' | 'lg'
  invalid?: boolean
  value?: string | number
}

@Component({
  selector: 'input[fc-text-input]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '',
  host: {
    class: 'fc-text-input',
    '[attr.aria-invalid]': 'invalid ? "true" : null',
    '[attr.data-size]': 'size === "md" ? null : size',
    '[attr.data-state]': 'invalid ? "error" : null',
    '(input)': 'onInput($event)',
  },
})
export class TextInput {
  @Input() size: NonNullable<TextInputProps['size']> = 'md'
  @Input() invalid = false
  @Input() value?: string | number
  @Output() valueChange = new EventEmitter<string>()

  onInput(event: Event): void {
    this.valueChange.emit((event.target as HTMLInputElement).value)
  }
}

// packages/react/src/tier1/TextInput.tsx
import React from 'react'
import { cx } from '../utils/cx'

export interface TextInputProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'size'>,
    React.RefAttributes<HTMLInputElement> {
  size?: 'sm' | 'md' | 'lg'
  invalid?: boolean
}

export function TextInput({ size = 'md', invalid, className, ref, ...props }: TextInputProps) {
  return (
    <input
      {...props}
      ref={ref}
      aria-invalid={invalid ? 'true' : props['aria-invalid']}
      data-size={size === 'md' ? undefined : size}
      data-state={invalid ? 'error' : undefined}
      className={cx('fc-text-input', className)}
    />
  )
}
