// packages/angular/src/tier3/Modal.ts
import {
  type AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  ElementRef,
  inject,
  InjectionToken,
  Input,
  type OnChanges,
  signal,
  type SimpleChanges,
} from '@angular/core'
import { createModal, type Modal as ModalMachine } from '@web-loom/foolscap-core'
import { nextId } from '../utils/ids'
import { attachToBody } from '../utils/portal'

export const MODAL = new InjectionToken<Modal>('fc-modal')

function injectModal(): Modal {
  const ctx = inject(MODAL, { optional: true })
  if (!ctx) throw new Error('Modal slot components must be used inside <Modal>')
  return ctx
}

export interface ModalProps {
  open: boolean
  variant?: 'default' | 'alert'
  size?: 'sm' | 'md' | 'lg' | 'full'
  closeOnBackdropClick?: boolean
  animationDuration?: number
}

export interface ModalTitleProps {
  id?: string
}

export interface ModalBodyProps {
  id?: string
}

@Component({
  selector: 'dialog[fc-modal]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-modal',
    '[class.fc-modal--alert]': 'variant === "alert"',
    '[class.fc-modal--sm]': 'size === "sm"',
    '[class.fc-modal--lg]': 'size === "lg"',
    '[class.fc-modal--full]': 'size === "full"',
    '[attr.aria-modal]': 'true',
    '[attr.aria-labelledby]': 'labelledBy()',
    '[attr.aria-describedby]': 'variant === "alert" ? describedBy() : null',
    '[attr.role]': 'variant === "alert" ? "alertdialog" : "dialog"',
    '[attr.data-state]': 'dialogOpen() ? "open" : "closed"',
    '[attr.data-variant]': 'variant',
    '[attr.data-size]': 'size',
    '(animationend)': 'onAnimationEnd()',
  },
  providers: [{ provide: MODAL, useExisting: Modal }],
})
export class Modal implements AfterViewInit, OnChanges {
  private readonly el = inject(ElementRef<HTMLDialogElement>)

  @Input({ required: true }) open = false
  @Input() variant: NonNullable<ModalProps['variant']> = 'default'
  @Input() size: NonNullable<ModalProps['size']> = 'md'
  @Input() closeOnBackdropClick = true
  @Input() animationDuration = 200

  private machine: ModalMachine | null = null
  private unsubscribe?: () => void

  readonly labelledBy = signal<string | undefined>(undefined)
  readonly describedBy = signal<string | undefined>(undefined)
  readonly dialogOpen = signal(false)

  constructor() {
    attachToBody(this.el.nativeElement)
    inject(DestroyRef).onDestroy(() => {
      this.unsubscribe?.()
      this.machine?.destroy()
      this.machine = null
    })
  }

  ngAfterViewInit(): void {
    const el = this.el.nativeElement
    const instance = createModal(el, {
      closeOnBackdropClick: this.closeOnBackdropClick,
      animationDuration: this.animationDuration,
    })
    this.machine = instance
    this.unsubscribe = instance.subscribe(() => this.syncOpen())
    if (this.open) instance.open()
    this.syncOpen()
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (!changes['open'] || !this.machine) return
    if (this.open) this.machine.open()
    else this.machine.close()
    this.syncOpen()
  }

  registerTitleId(id?: string): void {
    this.labelledBy.set(id)
  }

  registerBodyId(id?: string): void {
    this.describedBy.set(id)
  }

  requestClose(): void {
    this.machine?.close()
  }

  onAnimationEnd(): void {
    this.machine?.getRootProps().onAnimationEnd()
    this.syncOpen()
  }

  private syncOpen(): void {
    this.dialogOpen.set(this.el.nativeElement.open)
  }
}

@Component({
  selector: '[fc-modal-header]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-modal__header',
  },
})
export class ModalHeader {
  readonly kind = 'header'
}

@Component({
  selector: 'h2[fc-modal-title]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-modal__title',
    '[attr.id]': 'titleId',
  },
})
export class ModalTitle {
  private readonly ctx = injectModal()
  private readonly generatedId = nextId('fc-modal-title')

  @Input() id?: string

  get titleId(): string {
    return this.id ?? this.generatedId
  }

  constructor() {
    this.ctx.registerTitleId(this.titleId)
    inject(DestroyRef).onDestroy(() => this.ctx.registerTitleId(undefined))
  }
}

@Component({
  selector: '[fc-modal-body]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-modal__body',
    '[attr.id]': 'bodyId',
  },
})
export class ModalBody {
  private readonly ctx = injectModal()
  private readonly generatedId = nextId('fc-modal-body')

  @Input() id?: string

  get bodyId(): string {
    return this.id ?? this.generatedId
  }

  constructor() {
    this.ctx.registerBodyId(this.bodyId)
    inject(DestroyRef).onDestroy(() => this.ctx.registerBodyId(undefined))
  }
}

@Component({
  selector: '[fc-modal-footer]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-modal__footer',
  },
})
export class ModalFooter {
  readonly kind = 'footer'
}

@Component({
  selector: 'button[fc-modal-close]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-modal__close',
    '[attr.type]': '"button"',
    '[attr.aria-label]': 'ariaLabel ?? "Close modal"',
    '(click)': 'onClick()',
  },
})
export class ModalClose {
  private readonly ctx = injectModal()

  @Input('aria-label') ariaLabel?: string

  onClick(): void {
    this.ctx.requestClose()
  }
}

// packages/react/src/tier3/Modal.tsx
import React, {
  createContext,
  useContext,
  useEffect,
  useId,
  useReducer,
  useRef,
  useState,
} from 'react'
import { createPortal } from 'react-dom'
import { createModal, type Modal as ModalMachine } from '@web-loom/foolscap-core'
import { useCallbackRef } from '../utils/useCallbackRef'
import { cx } from '../utils/cx'

interface ModalContextValue {
  close: () => void
  registerTitleId: (id?: string) => void
  registerBodyId: (id?: string) => void
}

const ModalContext = createContext<ModalContextValue | null>(null)

function useModalContext(): ModalContextValue {
  const ctx = useContext(ModalContext)
  if (!ctx) throw new Error('Modal slot components must be used inside <Modal>')
  return ctx
}

export interface ModalProps extends Omit<
  React.DialogHTMLAttributes<HTMLDialogElement>,
  'open' | 'onClose' | 'children' | 'role' | 'aria-modal' | 'aria-labelledby' | 'aria-describedby'
> {
  open: boolean
  onClose: () => void
  variant?: 'default' | 'alert'
  size?: 'sm' | 'md' | 'lg' | 'full'
  closeOnBackdropClick?: boolean
  animationDuration?: number
  className?: string
  children: React.ReactNode
}

export function Modal({
  open,
  onClose,
  variant = 'default',
  size = 'md',
  closeOnBackdropClick = true,
  animationDuration = 200,
  className,
  children,
  ...props
}: ModalProps) {
  const dialogRef = useRef<HTMLDialogElement>(null)
  const machineRef = useRef<ModalMachine | null>(null)
  const [, forceUpdate] = useReducer((x: number) => x + 1, 0)
  const [labelledBy, setLabelledBy] = useState<string>()
  const [describedBy, setDescribedBy] = useState<string>()

  const stableOnClose = useCallbackRef(onClose)

  useEffect(() => {
    const el = dialogRef.current
    if (!el) return

    const machine = createModal(el, {
      closeOnBackdropClick,
      animationDuration,
      onClose: stableOnClose,
    })
    machineRef.current = machine
    const unsubscribe = machine.subscribe(() => forceUpdate())

    return () => {
      unsubscribe()
      machine.destroy()
      machineRef.current = null
    }
  }, [])

  useEffect(() => {
    const machine = machineRef.current
    if (!machine) return
    if (open) machine.open()
    else machine.close()
  }, [open])

  const rootProps = machineRef.current?.getRootProps()
  const dialogOpen = dialogRef.current?.open ?? false
  const handleAnimationEnd: React.AnimationEventHandler<HTMLDialogElement> = (event) => {
    props.onAnimationEnd?.(event)
    rootProps?.onAnimationEnd()
  }

  return createPortal(
    <dialog
      ref={dialogRef}
      {...props}
      aria-modal={true}
      aria-labelledby={labelledBy}
      aria-describedby={variant === 'alert' ? describedBy : undefined}
      role={variant === 'alert' ? 'alertdialog' : 'dialog'}
      data-state={dialogOpen ? 'open' : 'closed'}
      data-variant={variant}
      data-size={size}
      onAnimationEnd={handleAnimationEnd}
      className={cx(
        'fc-modal',
        variant !== 'default' && `fc-modal--${variant}`,
        size !== 'md' && `fc-modal--${size}`,
        className
      )}
    >
      <ModalContext.Provider
        value={{
          close: () => machineRef.current?.close(),
          registerTitleId: setLabelledBy,
          registerBodyId: setDescribedBy,
        }}
      >
        {children}
      </ModalContext.Provider>
    </dialog>,
    document.body
  )
}

export interface ModalHeaderProps extends React.HTMLAttributes<HTMLDivElement> {
  className?: string
  children: React.ReactNode
}

export function ModalHeader({ className, children, ...props }: ModalHeaderProps) {
  return (
    <div className={cx('fc-modal__header', className)} {...props}>
      {children}
    </div>
  )
}

export interface ModalTitleProps extends React.HTMLAttributes<HTMLHeadingElement> {
  className?: string
  children: React.ReactNode
}

export function ModalTitle({ className, children, id, ...props }: ModalTitleProps) {
  const reactId = useId().replace(/:/g, '')
  const generatedId = id ?? `fc-modal-title-${reactId}`
  const { registerTitleId } = useModalContext()

  useEffect(() => {
    registerTitleId(generatedId)
    return () => registerTitleId(undefined)
  }, [generatedId, registerTitleId])

  return (
    <h2 id={generatedId} className={cx('fc-modal__title', className)} {...props}>
      {children}
    </h2>
  )
}

export interface ModalBodyProps extends React.HTMLAttributes<HTMLDivElement> {
  className?: string
  children: React.ReactNode
}

export function ModalBody({ className, children, id, ...props }: ModalBodyProps) {
  const reactId = useId().replace(/:/g, '')
  const generatedId = id ?? `fc-modal-body-${reactId}`
  const { registerBodyId } = useModalContext()

  useEffect(() => {
    registerBodyId(generatedId)
    return () => registerBodyId(undefined)
  }, [generatedId, registerBodyId])

  return (
    <div id={generatedId} className={cx('fc-modal__body', className)} {...props}>
      {children}
    </div>
  )
}

export interface ModalFooterProps extends React.HTMLAttributes<HTMLDivElement> {
  className?: string
  children: React.ReactNode
}

export function ModalFooter({ className, children, ...props }: ModalFooterProps) {
  return (
    <div className={cx('fc-modal__footer', className)} {...props}>
      {children}
    </div>
  )
}

export interface ModalCloseProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  className?: string
  children?: React.ReactNode
}

export function ModalClose({ className, children, onClick, ...props }: ModalCloseProps) {
  const { close } = useModalContext()
  return (
    <button
      type="button"
      aria-label="Close modal"
      className={cx('fc-modal__close', className)}
      onClick={(e) => {
        close()
        onClick?.(e)
      }}
      {...props}
    >
      {children}
    </button>
  )
}
