// packages/angular/src/tier3/Pagination.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  EventEmitter,
  inject,
  InjectionToken,
  Injector,
  Input,
  type OnInit,
  Output,
  runInInjectionContext,
  signal,
} from '@angular/core'
import {
  createPagination,
  type Pagination as PaginationMachine,
  type PaginationPage,
} from '@web-loom/foolscap-core'
import { injectMachine } from '../bindings/inject-machine'
import { injectStableCallback } from '../bindings/inject-stable-callback'

export type { PaginationPage }

export const PAGINATION = new InjectionToken<PaginationRoot>('fc-pagination')

function injectPagination(): PaginationRoot {
  const ctx = inject(PAGINATION, { optional: true })
  if (!ctx) throw new Error('Pagination components must be used inside PaginationRoot')
  return ctx
}

export interface PaginationRootProps {
  totalPages: number
  page?: number
  defaultPage?: number
  siblingCount?: number
  getPageHref?: (page: number) => string
  size?: 'sm' | 'md' | 'lg'
}

export interface PaginationPageLinkProps {
  page: number
}

@Component({
  selector: 'button[fc-pagination-prev]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-pagination__prev',
    '[attr.type]': 'prevProps.type',
    '[attr.aria-label]': 'ariaLabel ?? prevProps["aria-label"]',
    '[attr.aria-disabled]': 'prevProps["aria-disabled"]',
    '[attr.data-state]': 'prevProps["data-state"]',
    '[disabled]': 'prevProps.disabled',
    '(click)': 'onClick()',
  },
})
export class PaginationPrev {
  private readonly ctx = injectPagination()

  @Input('aria-label') ariaLabel?: string

  get prevProps() {
    return this.ctx.machine.getPrevProps()
  }

  onClick(): void {
    this.ctx.machine.getPrevProps().onClick()
  }
}

@Component({
  selector: 'button[fc-pagination-next]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-pagination__next',
    '[attr.type]': 'nextProps.type',
    '[attr.aria-label]': 'ariaLabel ?? nextProps["aria-label"]',
    '[attr.aria-disabled]': 'nextProps["aria-disabled"]',
    '[attr.data-state]': 'nextProps["data-state"]',
    '[disabled]': 'nextProps.disabled',
    '(click)': 'onClick()',
  },
})
export class PaginationNext {
  private readonly ctx = injectPagination()

  @Input('aria-label') ariaLabel?: string

  get nextProps() {
    return this.ctx.machine.getNextProps()
  }

  onClick(): void {
    this.ctx.machine.getNextProps().onClick()
  }
}

@Component({
  selector: '[fc-pagination-page-link]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-pagination__link',
    '[attr.href]': 'href',
    '[attr.type]': 'href ? null : linkProps.type',
    '[attr.aria-label]': 'linkProps["aria-label"]',
    '[attr.aria-current]': 'linkProps["aria-current"]',
    '(click)': 'onClick()',
  },
})
export class PaginationPageLink {
  private readonly ctx = injectPagination()

  @Input({ required: true }) page!: number

  get linkProps() {
    return this.ctx.machine.getLinkProps(this.page)
  }

  get href(): string | null {
    return this.ctx.getPageHref?.(this.page) ?? null
  }

  onClick(): void {
    this.ctx.machine.getLinkProps(this.page).onClick()
  }
}

@Component({
  selector: '[fc-pagination-ellipsis]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-pagination__ellipsis',
    '[attr.aria-hidden]': 'true',
  },
})
export class PaginationEllipsis {
  readonly kind = 'ellipsis'
}

@Component({
  selector: 'ol[fc-pagination-list]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [PaginationPrev, PaginationNext, PaginationPageLink, PaginationEllipsis],
  template: `
    <li class="fc-pagination__item">
      <button fc-pagination-prev>‹ Prev</button>
    </li>
    @for (page of ctx.pages(); track $index) {
      <li class="fc-pagination__item">
        @if (page === 'ellipsis') {
          <span fc-pagination-ellipsis>…</span>
        } @else if (ctx.getPageHref) {
          <a fc-pagination-page-link [page]="page">{{ page }}</a>
        } @else {
          <button fc-pagination-page-link [page]="page">{{ page }}</button>
        }
      </li>
    }
    <li class="fc-pagination__item">
      <button fc-pagination-next>Next ›</button>
    </li>
  `,
  host: {
    class: 'fc-pagination__list',
  },
})
export class PaginationList {
  readonly ctx = injectPagination()
}

@Component({
  selector: 'nav[fc-pagination], fc-pagination',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [PaginationList],
  template: `<ol fc-pagination-list></ol>`,
  host: {
    class: 'fc-pagination',
    '[attr.aria-label]': 'ariaLabel ?? "Pagination"',
    '[attr.data-size]': 'size',
    '[attr.role]': '"navigation"',
  },
  providers: [{ provide: PAGINATION, useExisting: PaginationRoot }],
})
export class PaginationRoot implements OnInit {
  private readonly host = inject(ElementRef<HTMLElement>)
  private readonly injector = inject(Injector)

  @Input({ required: true }) totalPages = 1
  @Input() page?: number
  @Input() defaultPage?: number
  @Input() siblingCount?: number
  @Input() getPageHref?: (page: number) => string
  @Input() size?: PaginationRootProps['size']
  @Input('aria-label') ariaLabel?: string
  @Output() pageChange = new EventEmitter<number>()

  private readonly onPageChange = injectStableCallback(
    () => (next: number) => this.pageChange.emit(next),
  )

  machine!: PaginationMachine
  readonly pages = signal<PaginationPage[]>([])
  readonly currentPage = signal(1)

  ngOnInit(): void {
    const getTotalPages = () => this.totalPages
    const getPage = () => this.page
    const getSiblingCount = () => this.siblingCount
    this.machine = runInInjectionContext(this.injector, () =>
      injectMachine(() =>
        createPagination({
          get totalPages() {
            return getTotalPages()
          },
          get page() {
            return getPage()
          },
          defaultPage: this.defaultPage,
          get siblingCount() {
            return getSiblingCount()
          },
          onPageChange: this.onPageChange,
        }),
      ),
    )
    this.machine.setRootEl(this.host.nativeElement)
    this.sync()
    this.machine.subscribe(() => this.sync())
  }

  private sync(): void {
    this.pages.set([...this.machine.state.pages])
    this.currentPage.set(this.machine.state.currentPage)
  }
}

// packages/react/src/tier3/Pagination.tsx
import React, { createContext, useCallback, useContext, useRef } from 'react'
import {
  createPagination,
  type Pagination as PaginationMachine,
  type PaginationPage,
} from '@web-loom/foolscap-core'
import { useMachine } from '../hooks/useMachine'
import { useCallbackRef } from '../utils/useCallbackRef'
import { cx } from '../utils/cx'

interface PaginationContextValue {
  machine: PaginationMachine
  injectRootEl: (el: HTMLElement | null) => void
  getPageHref?: (page: number) => string
}

const PaginationContext = createContext<PaginationContextValue | null>(null)

function usePaginationContext(): PaginationContextValue {
  const ctx = useContext(PaginationContext)
  if (!ctx) throw new Error('Pagination components must be used inside PaginationRoot')
  return ctx
}

export interface PaginationRootProps
  extends Omit<React.HTMLAttributes<HTMLElement>, 'children'>,
    React.RefAttributes<HTMLElement> {
  totalPages: number
  page?: number
  defaultPage?: number
  siblingCount?: number
  onPageChange?: (page: number, prevPage: number) => void
  getPageHref?: (page: number) => string
  size?: 'sm' | 'md' | 'lg'
  className?: string
  children?: React.ReactNode
}

export function PaginationRoot({
  totalPages,
  page,
  defaultPage,
  siblingCount,
  onPageChange,
  getPageHref,
  size,
  className,
  children,
  ref,
  ...props
}: PaginationRootProps) {
  const totalPagesRef = useRef(totalPages)
  totalPagesRef.current = totalPages
  const pageRef = useRef(page)
  pageRef.current = page
  const siblingCountRef = useRef(siblingCount)
  siblingCountRef.current = siblingCount
  const defaultPageRef = useRef(defaultPage)
  const stableOnPageChange = useCallbackRef(onPageChange)

  const machine = useMachine(() =>
    createPagination({
      get totalPages() {
        return totalPagesRef.current
      },
      get page() {
        return pageRef.current
      },
      defaultPage: defaultPageRef.current,
      get siblingCount() {
        return siblingCountRef.current
      },
      onPageChange: stableOnPageChange,
    })
  )

  const injectRootEl = useCallback((el: HTMLElement | null) => machine.setRootEl(el), [machine])
  const rootProps = machine.getRootProps()

  return (
    <PaginationContext.Provider value={{ machine, injectRootEl, getPageHref }}>
      <nav
        {...props}
        aria-label={props['aria-label'] ?? rootProps['aria-label']}
        data-size={size}
        ref={(el) => {
          injectRootEl(el)
          if (typeof ref === 'function') ref(el)
          else if (ref) (ref as React.MutableRefObject<HTMLElement | null>).current = el
        }}
        className={cx('fc-pagination', className)}
      >
        {children ?? <PaginationList />}
      </nav>
    </PaginationContext.Provider>
  )
}

export interface PaginationListProps
  extends React.OlHTMLAttributes<HTMLOListElement>,
    React.RefAttributes<HTMLOListElement> {
  className?: string
}

export function PaginationList({ className, ref, ...props }: PaginationListProps) {
  const { machine } = usePaginationContext()
  const state = machine.state

  return (
    <ol {...props} ref={ref} className={cx('fc-pagination__list', className)}>
      <li className="fc-pagination__item">
        <PaginationPrev />
      </li>
      {state.pages.map((page, index) => (
        <li className="fc-pagination__item" key={`${page}-${index}`}>
          {page === 'ellipsis' ? <PaginationEllipsis /> : <PaginationPageLink page={page} />}
        </li>
      ))}
      <li className="fc-pagination__item">
        <PaginationNext />
      </li>
    </ol>
  )
}

export interface PaginationPrevProps
  extends Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, 'type'> {
  className?: string
}

export function PaginationPrev({ className, children = '‹ Prev', onClick, ...props }: PaginationPrevProps) {
  const { machine } = usePaginationContext()
  const prevProps = machine.getPrevProps()

  return (
    <button
      type={prevProps.type}
      {...props}
      aria-label={props['aria-label'] ?? prevProps['aria-label']}
      aria-disabled={prevProps['aria-disabled']}
      data-state={prevProps['data-state']}
      disabled={prevProps.disabled}
      onClick={(e) => {
        onClick?.(e)
        if (!e.defaultPrevented) prevProps.onClick()
      }}
      className={cx('fc-pagination__prev', className)}
    >
      {children}
    </button>
  )
}

export interface PaginationNextProps
  extends Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, 'type'> {
  className?: string
}

export function PaginationNext({ className, children = 'Next ›', onClick, ...props }: PaginationNextProps) {
  const { machine } = usePaginationContext()
  const nextProps = machine.getNextProps()

  return (
    <button
      type={nextProps.type}
      {...props}
      aria-label={props['aria-label'] ?? nextProps['aria-label']}
      aria-disabled={nextProps['aria-disabled']}
      data-state={nextProps['data-state']}
      disabled={nextProps.disabled}
      onClick={(e) => {
        onClick?.(e)
        if (!e.defaultPrevented) nextProps.onClick()
      }}
      className={cx('fc-pagination__next', className)}
    >
      {children}
    </button>
  )
}

export interface PaginationPageLinkProps {
  page: number
  className?: string
  children?: React.ReactNode
}

export function PaginationPageLink({ page, className, children }: PaginationPageLinkProps) {
  const { machine, getPageHref } = usePaginationContext()
  const linkProps = machine.getLinkProps(page)
  const href = getPageHref?.(page)
  const content = children ?? page

  if (href) {
    return (
      <a
        href={href}
        aria-label={linkProps['aria-label']}
        aria-current={linkProps['aria-current']}
        onClick={(e) => {
          if (!e.defaultPrevented) linkProps.onClick()
        }}
        className={cx('fc-pagination__link', className)}
      >
        {content}
      </a>
    )
  }

  return (
    <button
      type={linkProps.type}
      aria-label={linkProps['aria-label']}
      aria-current={linkProps['aria-current']}
      onClick={linkProps.onClick}
      className={cx('fc-pagination__link', className)}
    >
      {content}
    </button>
  )
}

export interface PaginationEllipsisProps extends React.HTMLAttributes<HTMLSpanElement> {
  className?: string
}

export function PaginationEllipsis({ className, children = '…', ...props }: PaginationEllipsisProps) {
  return (
    <span {...props} aria-hidden="true" className={cx('fc-pagination__ellipsis', className)}>
      {children}
    </span>
  )
}

export type { PaginationPage }
