// packages/angular/src/tier3/TreeView.ts
import { NgTemplateOutlet } from '@angular/common'
import {
  afterNextRender,
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  EventEmitter,
  inject,
  InjectionToken,
  Injector,
  Input,
  type OnInit,
  Output,
  runInInjectionContext,
  signal,
} from '@angular/core'
import {
  createTreeView,
  type TreeView as TreeViewMachine,
  type TreeViewItem,
  type TreeViewSelectionMode,
} from '@web-loom/foolscap-core'
import { injectMachine } from '../bindings/inject-machine'
import { injectStableCallback } from '../bindings/inject-stable-callback'

export type { TreeViewItem, TreeViewSelectionMode }

export const TREE_VIEW = new InjectionToken<TreeViewRoot>('fc-tree-view')

function injectTreeView(): TreeViewRoot {
  const ctx = inject(TREE_VIEW, { optional: true })
  if (!ctx) throw new Error('TreeView components must be used inside TreeViewRoot')
  return ctx
}

export interface TreeViewRootProps {
  items: TreeViewItem[]
  expandedIds?: string[]
  defaultExpandedIds?: string[]
  selectedId?: string | null
  defaultSelectedId?: string | null
  selectionMode?: TreeViewSelectionMode
  label?: string
}

export interface TreeViewItemProps {
  item: TreeViewItem
}

@Component({
  selector: '[fc-tree-label]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: { class: 'fc-tree__label' },
})
export class TreeViewLabel {
  readonly kind = 'label'
}

@Component({
  selector: 'button[fc-tree-toggle]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<span aria-hidden="true">{{ expanded ? '▾' : '▸' }}</span>`,
  host: {
    class: 'fc-tree__toggle',
    '[attr.type]': 'toggleProps.type',
    '[attr.tabindex]': 'toggleProps.tabIndex',
    '[attr.aria-label]': 'toggleProps["aria-label"]',
    '(click)': 'onClick($event)',
  },
})
export class TreeViewToggle {
  private readonly ctx = injectTreeView()
  @Input({ required: true }) item!: TreeViewItem

  get toggleProps() {
    return this.ctx.machine.getToggleProps(this.item.id)
  }

  get expanded() {
    return this.ctx.machine.getItemProps(this.item.id, true)['aria-expanded']
  }

  onClick(event: Event): void {
    event.stopPropagation()
    this.ctx.machine.getToggleProps(this.item.id).onClick()
  }
}

@Component({
  selector: '[fc-tree-item-content]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [TreeViewToggle, TreeViewLabel],
  template: `
    @if (item.children?.length) {
      <button fc-tree-toggle [item]="item"></button>
    } @else {
      <span class="fc-tree__spacer" aria-hidden="true"></span>
    }
    <span fc-tree-label>{{ item.label }}</span>
  `,
  host: { class: 'fc-tree__item-content' },
})
export class TreeViewItemContent {
  @Input({ required: true }) item!: TreeViewItem
}

@Component({
  selector: 'ul[fc-tree-group]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-tree__group',
    '[attr.role]': 'groupProps.role',
    '[attr.hidden]': 'groupProps.hidden ? "" : null',
  },
})
export class TreeViewGroup {
  private readonly ctx = injectTreeView()
  @Input({ required: true }) parent!: TreeViewItem

  get groupProps() {
    return this.ctx.machine.getGroupProps(this.parent.id)
  }
}

@Component({
  selector: 'ul[fc-tree], fc-tree',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgTemplateOutlet, TreeViewItemContent, TreeViewGroup],
  template: `
    <ng-template #node let-item>
      <li
        class="fc-tree__item"
        [attr.role]="itemProps(item).role"
        [attr.id]="itemProps(item).id"
        [attr.aria-label]="itemProps(item)['aria-label']"
        [attr.tabindex]="itemProps(item).tabIndex"
        [attr.aria-expanded]="itemProps(item)['aria-expanded']"
        [attr.aria-selected]="itemProps(item)['aria-selected']"
        [attr.aria-disabled]="itemProps(item)['aria-disabled']"
        [attr.aria-level]="itemProps(item)['aria-level']"
        [attr.data-state]="itemProps(item)['data-state']"
        [attr.data-disabled]="itemProps(item)['data-disabled']"
        [attr.data-item-id]="item.id"
        (click)="onItemClick(item, $event)"
        (keydown)="onItemKeyDown(item, $event)"
      >
        <div fc-tree-item-content [item]="item"></div>
        @if (item.children?.length) {
          <ul fc-tree-group [parent]="item">
            @for (child of item.children; track child.id) {
              <ng-container *ngTemplateOutlet="node; context: { $implicit: child }" />
            }
          </ul>
        }
      </li>
    </ng-template>
    @for (item of items; track item.id) {
      <ng-container *ngTemplateOutlet="node; context: { $implicit: item }" />
    }
  `,
  host: {
    class: 'fc-tree',
    '[attr.role]': 'rootProps.role',
    '[attr.aria-label]': 'label',
  },
  providers: [{ provide: TREE_VIEW, useExisting: TreeViewRoot }],
})
export class TreeViewRoot implements OnInit {
  private readonly host = inject(ElementRef<HTMLUListElement>)
  private readonly injector = inject(Injector)

  @Input({ required: true }) items: TreeViewItem[] = []
  @Input() expandedIds?: string[]
  @Input() defaultExpandedIds?: string[]
  @Input() selectedId?: string | null
  @Input() defaultSelectedId?: string | null
  @Input() selectionMode: TreeViewSelectionMode = 'single'
  @Input() label = 'Tree'
  @Output() expandedChange = new EventEmitter<string[]>()
  @Output() selectionChange = new EventEmitter<string | null>()

  private readonly onExpandedChange = injectStableCallback(
    () => (ids: string[]) => this.expandedChange.emit(ids),
  )
  private readonly onSelectionChange = injectStableCallback(
    () => (id: string | null) => this.selectionChange.emit(id),
  )

  machine!: TreeViewMachine
  readonly tick = signal(0)

  constructor() {
    afterNextRender(() => this.registerItems())
  }

  ngOnInit(): void {
    const getItems = () => this.items
    const getExpandedIds = () => this.expandedIds
    const getSelectedId = () => this.selectedId
    const getSelectionMode = () => this.selectionMode
    const getLabel = () => this.label
    this.machine = runInInjectionContext(this.injector, () =>
      injectMachine(() =>
        createTreeView({
          get items() {
            return getItems()
          },
          get expandedIds() {
            return getExpandedIds()
          },
          defaultExpandedIds: this.defaultExpandedIds,
          get selectedId() {
            return getSelectedId()
          },
          defaultSelectedId: this.defaultSelectedId,
          get selectionMode() {
            return getSelectionMode()
          },
          get label() {
            return getLabel()
          },
          onExpandedChange: this.onExpandedChange,
          onSelectionChange: this.onSelectionChange,
        }),
      ),
    )
    this.machine.setRootEl(this.host.nativeElement)
    this.machine.subscribe(() => {
      this.tick.update((n) => n + 1)
      queueMicrotask(() => this.registerItems())
    })
  }

  get rootProps() {
    return this.machine?.getRootProps() ?? { role: 'tree', 'aria-label': this.label }
  }

  itemProps(item: TreeViewItem) {
    void this.tick()
    return this.machine.getItemProps(item.id, Boolean(item.children?.length))
  }

  onItemClick(item: TreeViewItem, event: Event): void {
    event.stopPropagation()
    this.machine.getItemProps(item.id, Boolean(item.children?.length)).onClick()
  }

  onItemKeyDown(item: TreeViewItem, event: KeyboardEvent): void {
    event.stopPropagation()
    this.machine.getItemProps(item.id, Boolean(item.children?.length)).onKeyDown(event)
  }

  private registerItems(): void {
    this.host.nativeElement.querySelectorAll('.fc-tree__item').forEach((node: Element) => {
      const id = node.getAttribute('data-item-id')
      if (id && node instanceof HTMLLIElement) this.machine.setItemEl(id, node)
    })
  }
}

@Component({
  selector: 'li[fc-tree-item]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: { class: 'fc-tree__item' },
})
export class TreeViewItemView {
  @Input({ required: true }) item!: TreeViewItem
}

// packages/react/src/tier3/TreeView.tsx
import React, { createContext, useCallback, useContext, useRef } from 'react'
import {
  createTreeView,
  type TreeView as TreeViewMachine,
  type TreeViewItem,
  type TreeViewSelectionMode,
} from '@web-loom/foolscap-core'
import { useMachine } from '../hooks/useMachine'
import { useCallbackRef } from '../utils/useCallbackRef'
import { cx } from '../utils/cx'

interface TreeViewContextValue {
  machine: TreeViewMachine
  items: TreeViewItem[]
  injectRootEl: (el: HTMLUListElement | null) => void
  injectItemEl: (id: string, el: HTMLLIElement | null) => void
}

const TreeViewContext = createContext<TreeViewContextValue | null>(null)

function useTreeViewContext(): TreeViewContextValue {
  const ctx = useContext(TreeViewContext)
  if (!ctx) throw new Error('TreeView components must be used inside TreeViewRoot')
  return ctx
}

export type { TreeViewItem, TreeViewSelectionMode }

export interface TreeViewRootProps
  extends Omit<React.HTMLAttributes<HTMLUListElement>, 'children' | 'onSelect'>,
    React.RefAttributes<HTMLUListElement> {
  items: TreeViewItem[]
  expandedIds?: string[]
  defaultExpandedIds?: string[]
  selectedId?: string | null
  defaultSelectedId?: string | null
  selectionMode?: TreeViewSelectionMode
  label?: string
  onExpandedChange?: (ids: string[]) => void
  onSelectionChange?: (id: string) => void
  className?: string
  children?: React.ReactNode
}

export function TreeViewRoot({
  items,
  expandedIds,
  defaultExpandedIds,
  selectedId,
  defaultSelectedId,
  selectionMode = 'single',
  label = 'Tree',
  onExpandedChange,
  onSelectionChange,
  className,
  children,
  ref,
  ...props
}: TreeViewRootProps) {
  const itemsRef = useRef(items)
  itemsRef.current = items
  const expandedIdsRef = useRef(expandedIds)
  expandedIdsRef.current = expandedIds
  const defaultExpandedIdsRef = useRef(defaultExpandedIds)
  const selectedIdRef = useRef(selectedId)
  selectedIdRef.current = selectedId
  const defaultSelectedIdRef = useRef(defaultSelectedId)
  const selectionModeRef = useRef(selectionMode)
  selectionModeRef.current = selectionMode
  const labelRef = useRef(label)
  labelRef.current = label
  const stableOnExpandedChange = useCallbackRef(onExpandedChange)
  const stableOnSelectionChange = useCallbackRef(onSelectionChange)

  const machine = useMachine(() =>
    createTreeView({
      get items() {
        return itemsRef.current
      },
      get expandedIds() {
        return expandedIdsRef.current
      },
      defaultExpandedIds: defaultExpandedIdsRef.current,
      get selectedId() {
        return selectedIdRef.current
      },
      defaultSelectedId: defaultSelectedIdRef.current,
      get selectionMode() {
        return selectionModeRef.current
      },
      get label() {
        return labelRef.current
      },
      onExpandedChange: stableOnExpandedChange,
      onSelectionChange: stableOnSelectionChange,
    })
  )

  const injectRootEl = useCallback((el: HTMLUListElement | null) => machine.setRootEl(el), [machine])
  const injectItemEl = useCallback((id: string, el: HTMLLIElement | null) => machine.setItemEl(id, el), [machine])
  const rootProps = machine.getRootProps()

  return (
    <TreeViewContext.Provider value={{ machine, items, injectRootEl, injectItemEl }}>
      <ul
        {...props}
        role={rootProps.role}
        aria-label={props['aria-label'] ?? rootProps['aria-label']}
        ref={(el) => {
          injectRootEl(el)
          if (typeof ref === 'function') ref(el)
          else if (ref) (ref as React.MutableRefObject<HTMLUListElement | null>).current = el
        }}
        className={cx('fc-tree', className)}
      >
        {children ?? items.map((item) => <TreeViewItemView key={item.id} item={item} />)}
      </ul>
    </TreeViewContext.Provider>
  )
}

export interface TreeViewItemProps extends React.LiHTMLAttributes<HTMLLIElement> {
  item: TreeViewItem
  className?: string
}

export function TreeViewItemView({ item, className, children, ...props }: TreeViewItemProps) {
  const { machine, injectItemEl } = useTreeViewContext()
  const hasChildren = Boolean(item.children?.length)
  const itemProps = machine.getItemProps(item.id, hasChildren)

  return (
    <li
      {...props}
      role={itemProps.role}
      id={props.id ?? itemProps.id}
      aria-label={props['aria-label'] ?? itemProps['aria-label']}
      tabIndex={itemProps.tabIndex}
      aria-expanded={itemProps['aria-expanded']}
      aria-selected={itemProps['aria-selected']}
      aria-disabled={itemProps['aria-disabled']}
      aria-level={itemProps['aria-level']}
      data-state={itemProps['data-state']}
      data-disabled={itemProps['data-disabled']}
      onClick={(e) => {
        props.onClick?.(e)
        if (!e.defaultPrevented) {
          e.stopPropagation()
          itemProps.onClick()
        }
      }}
      onKeyDown={(e) => {
        props.onKeyDown?.(e)
        if (!e.defaultPrevented) {
          e.stopPropagation()
          itemProps.onKeyDown(e.nativeEvent)
        }
      }}
      ref={(el) => injectItemEl(item.id, el)}
      className={cx('fc-tree__item', className)}
    >
      {children ?? (
        <>
          <TreeViewItemContent item={item} />
          {hasChildren ? <TreeViewGroup parent={item} /> : null}
        </>
      )}
    </li>
  )
}

export interface TreeViewItemContentProps extends React.HTMLAttributes<HTMLDivElement> {
  item: TreeViewItem
  className?: string
}

export function TreeViewItemContent({ item, className, children, ...props }: TreeViewItemContentProps) {
  const hasChildren = Boolean(item.children?.length)
  return (
    <div {...props} className={cx('fc-tree__item-content', className)}>
      {hasChildren ? <TreeViewToggle item={item} /> : <span className="fc-tree__spacer" aria-hidden="true" />}
      <TreeViewLabel>{children ?? item.label}</TreeViewLabel>
    </div>
  )
}

export interface TreeViewToggleProps
  extends Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, 'type'> {
  item: TreeViewItem
  className?: string
}

export function TreeViewToggle({ item, className, children, ...props }: TreeViewToggleProps) {
  const { machine } = useTreeViewContext()
  const toggleProps = machine.getToggleProps(item.id)
  const expanded = machine.getItemProps(item.id, true)['aria-expanded']

  return (
    <button
      {...props}
      type={toggleProps.type}
      tabIndex={toggleProps.tabIndex}
      aria-label={props['aria-label'] ?? toggleProps['aria-label']}
      onClick={(e) => {
        e.stopPropagation()
        props.onClick?.(e)
        if (!e.defaultPrevented) toggleProps.onClick()
      }}
      className={cx('fc-tree__toggle', className)}
    >
      {children ?? <span aria-hidden="true">{expanded ? '▾' : '▸'}</span>}
    </button>
  )
}

export interface TreeViewLabelProps extends React.HTMLAttributes<HTMLSpanElement> {
  className?: string
}

export function TreeViewLabel({ className, ...props }: TreeViewLabelProps) {
  return <span {...props} className={cx('fc-tree__label', className)} />
}

export interface TreeViewGroupProps extends React.HTMLAttributes<HTMLUListElement> {
  parent: TreeViewItem
  className?: string
}

export function TreeViewGroup({ parent, className, ...props }: TreeViewGroupProps) {
  const { machine } = useTreeViewContext()
  const groupProps = machine.getGroupProps(parent.id)
  return (
    <ul
      {...props}
      role={groupProps.role}
      hidden={groupProps.hidden ? true : undefined}
      className={cx('fc-tree__group', className)}
    >
      {(parent.children ?? []).map((child) => (
        <TreeViewItemView key={child.id} item={child} />
      ))}
    </ul>
  )
}
