// packages/react/src/tier2/Accordion.tsx
import React, { createContext, useContext, useEffect, useRef } from 'react'
import { createAccordion, type Accordion } from '@web-loom/foolscap-core'
import { useMachine } from '../hooks/useMachine'
import { useCallbackRef } from '../utils/useCallbackRef'
import { cx } from '../utils/cx'

interface AccordionContextValue {
  machine: Accordion
}

const AccordionContext = createContext<AccordionContextValue | null>(null)

function useAccordionContext(): AccordionContextValue {
  const ctx = useContext(AccordionContext)
  if (!ctx) throw new Error('AccordionItem must be used inside AccordionRoot')
  return ctx
}

export interface AccordionRootProps {
  type?: 'single' | 'multiple'
  defaultValue?: string | string[]
  onValueChange?: (v: string | string[]) => void
  className?: string
  children: React.ReactNode
}

export function AccordionRoot({
  type = 'single',
  defaultValue,
  onValueChange,
  className,
  children,
}: AccordionRootProps) {
  const stableOnChange = useCallbackRef(onValueChange)
  const machine = useMachine(() =>
    createAccordion({ type, defaultValue, onValueChange: stableOnChange }),
  )

  return (
    <AccordionContext.Provider value={{ machine }}>
      <div className={cx('fc-accordion', className)} data-type={type}>
        {children}
      </div>
    </AccordionContext.Provider>
  )
}

export interface AccordionItemProps {
  value: string
  className?: string
  children: React.ReactNode
}

export function AccordionItem({ value, className, children }: AccordionItemProps) {
  const { machine } = useAccordionContext()
  const ref = useRef<HTMLDetailsElement>(null)

  useEffect(() => {
    const el = ref.current
    if (!el) return
    return machine.register({ value, detailsEl: el })
  }, [machine, value])

  const { value: stateValue } = machine.state
  const isOpen = Array.isArray(stateValue)
    ? stateValue.includes(value)
    : stateValue === value

  return (
    <details
      ref={ref}
      className={cx('fc-accordion__item', className)}
      data-state={isOpen ? 'open' : 'closed'}
    >
      {children}
    </details>
  )
}

export interface AccordionTriggerProps extends React.HTMLAttributes<HTMLElement> {
  className?: string
  children: React.ReactNode
}

export function AccordionTrigger({ className, children, ...props }: AccordionTriggerProps) {
  return (
    <summary className={cx('fc-accordion__trigger', className)} {...props}>
      {children}
    </summary>
  )
}

export interface AccordionPanelProps {
  className?: string
  children: React.ReactNode
}

export function AccordionPanel({ className, children }: AccordionPanelProps) {
  return <div className={cx('fc-accordion__panel', className)}>{children}</div>
}

// packages/angular/src/tier2/Accordion.ts
import {
  type AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  ElementRef,
  EventEmitter,
  inject,
  InjectionToken,
  Injector,
  Input,
  type OnInit,
  Output,
  runInInjectionContext,
  signal,
} from '@angular/core'
import { createAccordion, type Accordion } from '@web-loom/foolscap-core'
import { injectMachine } from '../bindings/inject-machine'
import { injectStableCallback } from '../bindings/inject-stable-callback'

export interface AccordionContext {
  machine: Accordion
  valueState: ReturnType<typeof signal<string | string[]>>
}

export const ACCORDION = new InjectionToken<AccordionRoot>('fc-accordion')

export interface AccordionRootProps {
  type?: 'single' | 'multiple'
  defaultValue?: string | string[]
}

@Component({
  selector: 'fc-accordion',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-accordion',
    '[attr.data-type]': 'type',
  },
  providers: [{ provide: ACCORDION, useExisting: AccordionRoot }],
})
export class AccordionRoot implements OnInit, AccordionContext {
  @Input() type: NonNullable<AccordionRootProps['type']> = 'single'
  @Input() defaultValue?: string | string[]
  @Output() valueChange = new EventEmitter<string | string[]>()

  private readonly injector = inject(Injector)
  private readonly onValueChange = injectStableCallback(
    () => (value: string | string[]) => this.valueChange.emit(value),
  )

  machine!: Accordion
  readonly valueState = signal<string | string[]>('')

  ngOnInit(): void {
    this.machine = runInInjectionContext(this.injector, () =>
      injectMachine(() =>
        createAccordion({
          type: this.type,
          defaultValue: this.defaultValue,
          onValueChange: this.onValueChange,
        }),
      ),
    )
    this.valueState.set(this.machine.state.value)
    this.machine.subscribe(() => {
      this.valueState.set(this.machine.state.value)
    })
  }
}

function injectAccordion(): AccordionRoot {
  const ctx = inject(ACCORDION, { optional: true })
  if (!ctx) throw new Error('AccordionItem must be used inside AccordionRoot')
  return ctx
}

export interface AccordionItemProps {
  value: string
}

@Component({
  selector: 'details[fc-accordion-item]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-accordion__item',
    '[attr.data-state]': 'isOpen ? "open" : "closed"',
  },
})
export class AccordionItem implements AfterViewInit, AccordionItemProps {
  private readonly el = inject(ElementRef<HTMLDetailsElement>)
  private readonly ctx = injectAccordion()
  private unregister?: () => void

  @Input({ required: true }) value!: string

  constructor() {
    inject(DestroyRef).onDestroy(() => this.unregister?.())
  }

  ngAfterViewInit(): void {
    this.unregister = this.ctx.machine.register({
      value: this.value,
      detailsEl: this.el.nativeElement,
    })
  }

  get isOpen(): boolean {
    const stateValue = this.ctx.valueState()
    return Array.isArray(stateValue) ? stateValue.includes(this.value) : stateValue === this.value
  }
}

@Component({
  selector: 'summary[fc-accordion-trigger]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-accordion__trigger',
  },
})
export class AccordionTrigger {
  readonly role = 'trigger'
}

@Component({
  selector: '[fc-accordion-panel]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-accordion__panel',
  },
})
export class AccordionPanel {
  readonly role = 'panel'
}
