// packages/react/src/tier2/Form.tsx
import React, { createContext, useContext, useEffect, useReducer, useRef } from 'react'
import {
  createForm,
  type Form as FormMachine,
  type FieldConfig,
  type FormOptions,
} from '@web-loom/foolscap-core'
import { useCallbackRef } from '../utils/useCallbackRef'
import { cx } from '../utils/cx'

export type { FieldConfig }

// ─── Context ──────────────────────────────────────────────────────────────────

interface FormContextValue {
  machine: FormMachine | null
}

const FormContext = createContext<FormContextValue>({ machine: null })

export function useFormContext(): FormContextValue {
  return useContext(FormContext)
}

// ─── Root ──────────────────────────────────────────────────────────────────────

export interface FormRootProps
  extends Omit<React.FormHTMLAttributes<HTMLFormElement>, 'onSubmit' | 'onInvalid'> {
  fields?: FormOptions['fields']
  onSubmit?: FormOptions['onSubmit']
  onInvalid?: FormOptions['onInvalid']
  className?: string
  children: React.ReactNode
}

export function FormRoot({
  fields,
  onSubmit,
  onInvalid,
  className,
  children,
  ...props
}: FormRootProps) {
  const formRef = useRef<HTMLFormElement>(null)
  const machineRef = useRef<FormMachine | null>(null)
  const [, forceUpdate] = useReducer((x: number) => x + 1, 0)

  const stableOnSubmit = useCallbackRef(onSubmit)
  const stableOnInvalid = useCallbackRef(onInvalid)

  useEffect(() => {
    const el = formRef.current
    if (!el) return

    const machine = createForm(el, {
      fields,
      onSubmit: stableOnSubmit,
      onInvalid: stableOnInvalid,
    })
    machineRef.current = machine
    const unsubscribe = machine.subscribe(() => forceUpdate())

    return () => {
      unsubscribe()
      machine.destroy()
      machineRef.current = null
    }
  }, [])

  const formProps = machineRef.current?.getFormProps()
  const state = machineRef.current?.state ?? { errors: {}, isSubmitting: false, touched: {} }

  return (
    <FormContext.Provider value={{ machine: machineRef.current }}>
      <form
        ref={formRef}
        {...props}
        noValidate={formProps?.noValidate ?? true}
        onSubmit={
          formProps
            ? (e) => formProps.onSubmit(e.nativeEvent as SubmitEvent)
            : undefined
        }
        data-state={
          state.isSubmitting
            ? 'submitting'
            : Object.keys(state.errors).length > 0
              ? 'error'
              : 'idle'
        }
        className={cx('fc-form', className)}
      >
        {children}
      </form>
    </FormContext.Provider>
  )
}

// ─── Error summary ─────────────────────────────────────────────────────────────

export interface FormErrorSummaryProps extends React.HTMLAttributes<HTMLDivElement> {
  heading?: string
  className?: string
}

export function FormErrorSummary({
  heading = 'Please fix the following errors:',
  className,
  ...props
}: FormErrorSummaryProps) {
  const { machine } = useFormContext()
  const errors = machine?.state.errors ?? {}
  const hasErrors = Object.keys(errors).length > 0

  return (
    <div
      role="alert"
      hidden={!hasErrors}
      className={cx('fc-form__error-summary', className)}
      {...props}
    >
      <p>{heading}</p>
      <ul>
        {Object.entries(errors).map(([name, message]) => (
          <li key={name}>
            <a href={`#${name}`}>{message}</a>
          </li>
        ))}
      </ul>
    </div>
  )
}

// ─── Fields ────────────────────────────────────────────────────────────────────

export interface FormFieldsProps extends React.HTMLAttributes<HTMLDivElement> {
  className?: string
  children: React.ReactNode
}

export function FormFields({ className, children, ...props }: FormFieldsProps) {
  return (
    <div className={cx('fc-form__fields', className)} {...props}>
      {children}
    </div>
  )
}

// ─── Actions ───────────────────────────────────────────────────────────────────

export interface FormActionsProps extends React.HTMLAttributes<HTMLDivElement> {
  className?: string
  children: React.ReactNode
}

export function FormActions({ className, children, ...props }: FormActionsProps) {
  return (
    <div className={cx('fc-form__actions', className)} {...props}>
      {children}
    </div>
  )
}

// packages/angular/src/tier2/Form.ts
import {
  type AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  ElementRef,
  EventEmitter,
  inject,
  InjectionToken,
  Input,
  Output,
  signal,
} from '@angular/core'
import {
  createForm,
  type FieldConfig,
  type Form as FormMachine,
  type FormOptions,
} from '@web-loom/foolscap-core'
import { injectStableCallback } from '../bindings/inject-stable-callback'

export type { FieldConfig }

export const FORM = new InjectionToken<FormRoot>('fc-form')

export interface FormRootProps {
  fields?: FormOptions['fields']
}

export interface FormErrorSummaryProps {
  heading?: string
}

@Component({
  selector: 'form[fc-form]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-form',
    '[attr.novalidate]': 'true',
    '[attr.data-state]': 'dataState()',
    '(submit)': 'onSubmit($event)',
  },
  providers: [{ provide: FORM, useExisting: FormRoot }],
})
export class FormRoot implements AfterViewInit {
  @Input() fields?: FormOptions['fields']
  @Output() formSubmit = new EventEmitter<Record<string, string>>()
  @Output() invalid = new EventEmitter<Record<string, string>>()

  private readonly el = inject(ElementRef<HTMLFormElement>)
  private readonly onSubmitCallback = injectStableCallback(
    () => (values: Record<string, string>) => this.formSubmit.emit(values),
  )
  private readonly onInvalidCallback = injectStableCallback(
    () => (errors: Record<string, string>) => this.invalid.emit(errors),
  )

  machine: FormMachine | null = null
  readonly errors = signal<Record<string, string>>({})
  readonly dataState = signal<'idle' | 'error' | 'submitting'>('idle')
  private unsubscribe?: () => void

  constructor() {
    inject(DestroyRef).onDestroy(() => {
      this.unsubscribe?.()
      this.machine?.destroy()
      this.machine = null
    })
  }

  ngAfterViewInit(): void {
    const el = this.el.nativeElement
    const getFields = () => this.fields
    const instance = createForm(el, {
      get fields() {
        return getFields()
      },
      onSubmit: this.onSubmitCallback,
      onInvalid: this.onInvalidCallback,
    })
    this.machine = instance
    this.unsubscribe = instance.subscribe(() => this.syncFromMachine())
    this.syncFromMachine()
  }

  getFieldProps(name: string) {
    return (
      this.machine?.getFieldProps(name) ?? {
        name,
        'aria-invalid': false,
        'aria-describedby': `${name}-error`,
        onBlur: () => undefined,
      }
    )
  }

  getErrorProps(name: string) {
    return (
      this.machine?.getErrorProps(name) ?? {
        id: `${name}-error`,
        role: 'alert' as const,
        hidden: true,
      }
    )
  }

  onSubmit(event: Event): void {
    event.preventDefault()
    this.machine?.getFormProps().onSubmit(event as SubmitEvent)
  }

  private syncFromMachine(): void {
    const state = this.machine?.state
    if (!state) return
    this.errors.set({ ...state.errors })
    this.dataState.set(
      state.isSubmitting ? 'submitting' : Object.keys(state.errors).length > 0 ? 'error' : 'idle',
    )
  }
}

export function injectFormContext(): FormRoot | null {
  return inject(FORM, { optional: true })
}

/** Cross-framework alias matching Vue `useFormContext`. */
export const useFormContext = injectFormContext

@Component({
  selector: '[fc-form-error-summary]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <p>{{ heading }}</p>
    <ul>
      @for (entry of errorEntries; track entry.name) {
        <li>
          <a [href]="'#' + entry.name">{{ entry.message }}</a>
        </li>
      }
    </ul>
  `,
  host: {
    class: 'fc-form__error-summary',
    '[attr.role]': '"alert"',
    '[attr.hidden]': 'hasErrors ? null : ""',
  },
})
export class FormErrorSummary {
  private readonly form = injectFormContext()

  @Input() heading = 'Please fix the following errors:'

  get hasErrors(): boolean {
    return Object.keys(this.form?.errors() ?? {}).length > 0
  }

  get errorEntries(): { name: string; message: string }[] {
    return Object.entries(this.form?.errors() ?? {}).map(([name, message]) => ({ name, message }))
  }
}

@Component({
  selector: '[fc-form-fields]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-form__fields',
  },
})
export class FormFields {
  readonly role = 'fields'
}

@Component({
  selector: '[fc-form-actions]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    class: 'fc-form__actions',
  },
})
export class FormActions {
  readonly role = 'actions'
}
