// packages/react/src/tier2/Popover.tsx
import React, {
  cloneElement,
  createContext,
  useContext,
  useEffect,
  useReducer,
  useRef,
  useState,
} from 'react'
import { createPopover, type Popover as PopoverMachine } from '@web-loom/foolscap-core'
import { useCallbackRef } from '../utils/useCallbackRef'
import { cx } from '../utils/cx'

type PopoverPlacement = 'top' | 'bottom' | 'left' | 'right'

interface PopoverContextValue {
  machine: PopoverMachine | null
  placement: PopoverPlacement
  setTriggerEl: (el: HTMLElement | null) => void
  setContentEl: (el: HTMLElement | null) => void
  close: () => void
}

const PopoverContext = createContext<PopoverContextValue | null>(null)

function usePopoverContext(): PopoverContextValue {
  const ctx = useContext(PopoverContext)
  if (!ctx) throw new Error('PopoverTrigger and PopoverContent must be used inside PopoverRoot')
  return ctx
}

function assignRef<T>(ref: React.Ref<T> | undefined, value: T | null): void {
  if (typeof ref === 'function') {
    ref(value)
  } else if (ref && typeof ref === 'object') {
    ;(ref as React.MutableRefObject<T | null>).current = value
  }
}

function mergeRefs<T>(...refs: Array<React.Ref<T> | undefined>) {
  return (value: T | null) => {
    refs.forEach((ref) => assignRef(ref, value))
  }
}

function mergeHandlers<E>(
  first?: (event: E) => void,
  second?: (event: E) => void
): (event: E) => void {
  return (event: E) => {
    first?.(event)
    second?.(event)
  }
}

function getElementRef<T>(element: React.ReactElement<T>): React.Ref<unknown> | undefined {
  const typedElement = element as React.ReactElement<T> & {
    ref?: React.Ref<unknown>
    props: T & { ref?: React.Ref<unknown> }
  }
  return typedElement.ref ?? typedElement.props.ref
}

export interface PopoverRootProps {
  open?: boolean
  defaultOpen?: boolean
  onOpenChange?: (open: boolean) => void
  placement?: PopoverPlacement
  offset?: number
  children: React.ReactNode
}

export function PopoverRoot({
  open,
  defaultOpen,
  onOpenChange,
  placement = 'bottom',
  offset = 8,
  children,
}: PopoverRootProps) {
  const [triggerEl, setTriggerEl] = useState<HTMLElement | null>(null)
  const [contentEl, setContentEl] = useState<HTMLElement | null>(null)
  const machineRef = useRef<PopoverMachine | null>(null)
  const [, forceUpdate] = useReducer((x: number) => x + 1, 0)
  const stableOnOpenChange = useCallbackRef(onOpenChange)
  const didApplyDefaultOpen = useRef(false)

  useEffect(() => {
    if (!triggerEl || !contentEl) return

    const machine = createPopover(triggerEl, contentEl, {
      placement,
      offset,
      onOpen: () => stableOnOpenChange(true),
      onClose: () => stableOnOpenChange(false),
    })

    machineRef.current = machine
    const unsubscribe = machine.subscribe(() => forceUpdate())
    forceUpdate()

    if (defaultOpen && !didApplyDefaultOpen.current) {
      didApplyDefaultOpen.current = true
      void machine.open()
    }

    return () => {
      unsubscribe()
      machine.destroy()
      machineRef.current = null
    }
  }, [triggerEl, contentEl, placement, offset, defaultOpen, stableOnOpenChange])

  useEffect(() => {
    const machine = machineRef.current
    if (!machine || open === undefined) return
    if (open && !machine.state.open) {
      void machine.open()
    } else if (!open && machine.state.open) {
      machine.close()
    }
  }, [open])

  const machine = machineRef.current

  return (
    <PopoverContext.Provider
      value={{
        machine,
        placement,
        setTriggerEl,
        setContentEl,
        close: () => machine?.close(),
      }}
    >
      {children}
    </PopoverContext.Provider>
  )
}

export interface PopoverTriggerProps {
  asChild?: boolean
  children: React.ReactElement
}

export function PopoverTrigger({ asChild = true, children }: PopoverTriggerProps) {
  const { machine, setTriggerEl } = usePopoverContext()
  void asChild

  const triggerProps = machine?.getTriggerProps()
  const contentProps = machine?.getContentProps()
  const childProps = children.props as Record<string, unknown>

  const mergedProps = {
    ...triggerProps,
    'aria-haspopup': 'dialog',
    'aria-expanded': triggerProps?.['aria-expanded'] ?? false,
    'aria-controls': contentProps?.id ?? triggerProps?.['aria-controls'],
    onClick: mergeHandlers(
      childProps.onClick as ((event: unknown) => void) | undefined,
      triggerProps?.onClick
    ),
    ref: mergeRefs(getElementRef(children), setTriggerEl),
  }

  return cloneElement(children, mergedProps)
}

export interface PopoverContentProps
  extends React.HTMLAttributes<HTMLDivElement>,
    React.RefAttributes<HTMLDivElement> {
  className?: string
  children: React.ReactNode
}

export function PopoverContent({ className, children, ref, style, ...props }: PopoverContentProps) {
  const { machine, placement, setContentEl } = usePopoverContext()
  const contentProps = machine?.getContentProps()

  // Strip `display` from user styles — the machine owns style.display via inline assignment
  // and React must not overwrite it on every re-render.
  const { display: _display, ...safeStyle } = (style ?? {}) as React.CSSProperties & {
    display?: string
  }

  return (
    <div
      {...props}
      {...contentProps}
      ref={mergeRefs(ref, setContentEl)}
      style={safeStyle}
      data-state={contentProps?.['data-state'] ?? 'closed'}
      data-placement={placement}
      hidden={contentProps?.hidden ?? true}
      className={cx('fc-popover', className)}
    >
      <span className="fc-popover__arrow" aria-hidden="true" />
      {children}
    </div>
  )
}

export interface PopoverCloseProps {
  children: React.ReactElement
}

export function PopoverClose({ children }: PopoverCloseProps) {
  const { close } = usePopoverContext()
  const childProps = children.props as Record<string, unknown>
  const childElement = children as React.ReactElement<Record<string, unknown>>

  return cloneElement(childElement, {
    onClick: mergeHandlers(childProps.onClick as ((event: unknown) => void) | undefined, () => {
      close()
    }),
  })
}

// packages/angular/src/tier2/Popover.ts
import {
  afterNextRender,
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  Directive,
  ElementRef,
  EventEmitter,
  inject,
  InjectionToken,
  Input,
  type OnChanges,
  Output,
  signal,
  type SimpleChanges,
} from '@angular/core'
import { createPopover, type Popover as PopoverMachine } from '@web-loom/foolscap-core'
import { injectStableCallback } from '../bindings/inject-stable-callback'

export type PopoverPlacement = 'top' | 'bottom' | 'left' | 'right'

export const POPOVER = new InjectionToken<PopoverRoot>('fc-popover')

function injectPopover(): PopoverRoot {
  const ctx = inject(POPOVER, { optional: true })
  if (!ctx) throw new Error('PopoverTrigger and PopoverContent must be used inside PopoverRoot')
  return ctx
}

export interface PopoverRootProps {
  open?: boolean
  defaultOpen?: boolean
  placement?: PopoverPlacement
  offset?: number
}

@Component({
  selector: 'fc-popover-root',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  providers: [{ provide: POPOVER, useExisting: PopoverRoot }],
})
export class PopoverRoot implements OnChanges {
  @Input() open?: boolean
  @Input() defaultOpen = false
  @Input() placement: NonNullable<PopoverRootProps['placement']> = 'bottom'
  @Input() offset = 8
  @Output() openChange = new EventEmitter<boolean>()

  private triggerEl: HTMLElement | null = null
  private contentEl: HTMLElement | null = null
  private machine: PopoverMachine | null = null
  private unsubscribe?: () => void
  private didApplyDefaultOpen = false
  private readonly onOpen = injectStableCallback(() => () => this.openChange.emit(true))
  private readonly onClose = injectStableCallback(() => () => this.openChange.emit(false))

  readonly isOpen = signal(false)
  readonly contentId = signal<string | undefined>(undefined)

  constructor() {
    inject(DestroyRef).onDestroy(() => this.teardown())
    afterNextRender(() => this.syncMachine())
  }

  ngOnChanges(changes: SimpleChanges): void {
    if ((changes['placement'] || changes['offset']) && this.machine) {
      this.syncMachine()
      return
    }
    if (changes['open'] && this.machine) {
      this.applyControlledOpen()
    }
  }

  setTriggerEl(el: HTMLElement | null): void {
    if (this.triggerEl === el) return
    this.triggerEl = el
    this.syncMachine()
  }

  setContentEl(el: HTMLElement | null): void {
    if (this.contentEl === el) return
    this.contentEl = el
    this.syncMachine()
  }

  close(): void {
    this.machine?.close()
  }

  triggerClick(): void {
    this.machine?.getTriggerProps().onClick()
  }

  private teardown(): void {
    this.unsubscribe?.()
    this.unsubscribe = undefined
    this.machine?.destroy()
    this.machine = null
  }

  private applyControlledOpen(): void {
    const instance = this.machine
    if (!instance || this.open === undefined) return
    if (this.open && !instance.state.open) void instance.open()
    else if (!this.open && instance.state.open) instance.close()
  }

  private syncMachine(): void {
    this.teardown()
    const trigger = this.triggerEl
    const content = this.contentEl
    if (!trigger || !content) return

    const instance = createPopover(trigger, content, {
      placement: this.placement,
      offset: this.offset,
      onOpen: this.onOpen,
      onClose: this.onClose,
    })
    this.machine = instance
    this.contentId.set(instance.getContentProps().id)
    this.unsubscribe = instance.subscribe(() => {
      this.isOpen.set(instance.state.open)
    })
    this.isOpen.set(instance.state.open)

    if (this.open !== undefined) {
      this.applyControlledOpen()
    } else if (this.defaultOpen && !this.didApplyDefaultOpen) {
      this.didApplyDefaultOpen = true
      void instance.open()
    }
  }
}

@Directive({
  selector: '[fc-popover-trigger]',
  standalone: true,
  host: {
    '[attr.aria-haspopup]': '"dialog"',
    '[attr.aria-expanded]': 'ctx.isOpen()',
    '[attr.aria-controls]': 'ctx.contentId()',
    '(click)': 'onClick()',
  },
})
export class PopoverTrigger {
  protected readonly ctx = injectPopover()

  constructor() {
    this.ctx.setTriggerEl(inject(ElementRef<HTMLElement>).nativeElement)
  }

  onClick(): void {
    this.ctx.triggerClick()
  }
}

@Component({
  selector: '[fc-popover-content]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <span class="fc-popover__arrow" aria-hidden="true"></span>
    <ng-content />
  `,
  host: {
    class: 'fc-popover',
    '[attr.role]': '"dialog"',
    '[attr.id]': 'ctx.contentId()',
    '[attr.data-state]': 'ctx.isOpen() ? "open" : "closed"',
    '[attr.data-placement]': 'ctx.placement',
    '[attr.hidden]': 'ctx.isOpen() ? null : ""',
  },
})
export class PopoverContent {
  protected readonly ctx = injectPopover()

  constructor() {
    this.ctx.setContentEl(inject(ElementRef<HTMLElement>).nativeElement)
  }
}

@Directive({
  selector: '[fc-popover-close]',
  standalone: true,
  host: {
    '(click)': 'onClick()',
  },
})
export class PopoverClose {
  private readonly ctx = injectPopover()

  onClick(): void {
    this.ctx.close()
  }
}
